"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from latitudesh_python_sdk.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class BandwidthPlanDataType(str, Enum):
    BANDWIDTH_PLAN = "bandwidth_plan"


class UsdTypedDict(TypedDict):
    monthly: NotRequired[int]
    hourly: NotRequired[int]


class Usd(BaseModel):
    monthly: Optional[int] = None

    hourly: Optional[int] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["monthly", "hourly"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class BrlTypedDict(TypedDict):
    monthly: NotRequired[int]
    hourly: NotRequired[int]


class Brl(BaseModel):
    monthly: Optional[int] = None

    hourly: Optional[int] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["monthly", "hourly"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class PricingTypedDict(TypedDict):
    usd: NotRequired[UsdTypedDict]
    brl: NotRequired[BrlTypedDict]


class Pricing(BaseModel):
    usd: Optional[Usd] = None

    brl: Optional[Brl] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["usd", "brl"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class BandwidthPlanDataAttributesTypedDict(TypedDict):
    region: NotRequired[str]
    locations: NotRequired[List[str]]
    pricing: NotRequired[PricingTypedDict]


class BandwidthPlanDataAttributes(BaseModel):
    region: Optional[str] = None

    locations: Optional[List[str]] = None

    pricing: Optional[Pricing] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["region", "locations", "pricing"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class BandwidthPlanDataTypedDict(TypedDict):
    id: NotRequired[str]
    type: NotRequired[BandwidthPlanDataType]
    attributes: NotRequired[BandwidthPlanDataAttributesTypedDict]


class BandwidthPlanData(BaseModel):
    id: Optional[str] = None

    type: Optional[BandwidthPlanDataType] = None

    attributes: Optional[BandwidthPlanDataAttributes] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["id", "type", "attributes"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
