"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from latitudesh_python_sdk.types import BaseModel
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class CreateAPIKeyType(str, Enum):
    API_KEYS = "api_keys"


class CreateAPIKeyAttributesTypedDict(TypedDict):
    name: NotRequired[str]
    r"""Name of the API Key"""
    read_only: NotRequired[bool]
    r"""Whether the API Key is read-only. Read-only keys can only perform GET, HEAD, and OPTIONS requests."""
    allowed_ips: NotRequired[List[str]]
    r"""List of allowed IP addresses or CIDR ranges. If set, the API key can only be used from these IP addresses."""


class CreateAPIKeyAttributes(BaseModel):
    name: Optional[str] = "Name of the API Key"
    r"""Name of the API Key"""

    read_only: Optional[bool] = None
    r"""Whether the API Key is read-only. Read-only keys can only perform GET, HEAD, and OPTIONS requests."""

    allowed_ips: Optional[List[str]] = None
    r"""List of allowed IP addresses or CIDR ranges. If set, the API key can only be used from these IP addresses."""


class DataTypedDict(TypedDict):
    type: CreateAPIKeyType
    attributes: NotRequired[CreateAPIKeyAttributesTypedDict]


class Data(BaseModel):
    type: CreateAPIKeyType

    attributes: Optional[CreateAPIKeyAttributes] = None


class CreateAPIKeyTypedDict(TypedDict):
    data: NotRequired[DataTypedDict]


class CreateAPIKey(BaseModel):
    data: Optional[Data] = None
