"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .volume_data import VolumeData, VolumeDataTypedDict
from enum import Enum
from latitudesh_python_sdk.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class CreateVolumeBlockStorageType(str, Enum):
    VOLUMES = "volumes"


class CreateVolumeBlockStorageAttributesTypedDict(TypedDict):
    project: str
    r"""Project ID or slug"""
    name: str
    r"""Volume name"""
    region: str
    r"""Region (site) slug where the volume is provisioned"""
    size_in_gb: int
    r"""Size in GB"""


class CreateVolumeBlockStorageAttributes(BaseModel):
    project: str
    r"""Project ID or slug"""

    name: str
    r"""Volume name"""

    region: str
    r"""Region (site) slug where the volume is provisioned"""

    size_in_gb: int
    r"""Size in GB"""


class CreateVolumeBlockStorageDataTypedDict(TypedDict):
    type: CreateVolumeBlockStorageType
    attributes: CreateVolumeBlockStorageAttributesTypedDict


class CreateVolumeBlockStorageData(BaseModel):
    type: CreateVolumeBlockStorageType

    attributes: CreateVolumeBlockStorageAttributes


class CreateVolumeBlockStorageRequestBodyTypedDict(TypedDict):
    data: CreateVolumeBlockStorageDataTypedDict


class CreateVolumeBlockStorageRequestBody(BaseModel):
    data: CreateVolumeBlockStorageData


class CreateVolumeResponseBodyTypedDict(TypedDict):
    r"""Created"""

    data: NotRequired[VolumeDataTypedDict]


class CreateVolumeResponseBody(BaseModel):
    r"""Created"""

    data: Optional[VolumeData] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["data"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
