"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .virtual_machine_network_attachment_create_payload import (
    VirtualMachineNetworkAttachmentCreatePayload,
    VirtualMachineNetworkAttachmentCreatePayloadTypedDict,
)
from latitudesh_python_sdk.types import BaseModel, UNSET_SENTINEL
from latitudesh_python_sdk.utils import (
    FieldMetadata,
    PathParamMetadata,
    RequestMetadata,
)
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class CreateVirtualMachineNetworkAttachmentRequestTypedDict(TypedDict):
    virtual_machine_id: str
    virtual_machine_network_attachment_create_payload: (
        VirtualMachineNetworkAttachmentCreatePayloadTypedDict
    )


class CreateVirtualMachineNetworkAttachmentRequest(BaseModel):
    virtual_machine_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    virtual_machine_network_attachment_create_payload: Annotated[
        VirtualMachineNetworkAttachmentCreatePayload,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]


class CreateVirtualMachineNetworkAttachmentMetaTypedDict(TypedDict):
    status: NotRequired[str]


class CreateVirtualMachineNetworkAttachmentMeta(BaseModel):
    status: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["status"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class CreateVirtualMachineNetworkAttachmentResponseBodyTypedDict(TypedDict):
    r"""Accepted"""

    meta: NotRequired[CreateVirtualMachineNetworkAttachmentMetaTypedDict]


class CreateVirtualMachineNetworkAttachmentResponseBody(BaseModel):
    r"""Accepted"""

    meta: Optional[CreateVirtualMachineNetworkAttachmentMeta] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["meta"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
