"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .create_bgp_session import CreateBgpSession, CreateBgpSessionTypedDict
from latitudesh_python_sdk.types import BaseModel
from latitudesh_python_sdk.utils import (
    FieldMetadata,
    PathParamMetadata,
    RequestMetadata,
)
from typing_extensions import Annotated, TypedDict


class CreateElasticIPBgpSessionRequestTypedDict(TypedDict):
    elastic_ip_id: str
    create_bgp_session: CreateBgpSessionTypedDict


class CreateElasticIPBgpSessionRequest(BaseModel):
    elastic_ip_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    create_bgp_session: Annotated[
        CreateBgpSession,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
