"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from latitudesh_python_sdk.types import BaseModel, UNSET_SENTINEL
from latitudesh_python_sdk.utils import (
    FieldMetadata,
    PathParamMetadata,
    RequestMetadata,
)
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class CreateServerReinstallServersType(str, Enum):
    REINSTALLS = "reinstalls"


class CreateServerReinstallServersOperatingSystem(str, Enum):
    r"""The OS selected for the reinstall process"""

    CENTOS_7_4_X64 = "centos_7_4_x64"
    CENTOS_8_X64 = "centos_8_x64"
    DEBIAN_10 = "debian_10"
    DEBIAN_11 = "debian_11"
    DEBIAN_12 = "debian_12"
    IPXE = "ipxe"
    RHEL8 = "rhel8"
    ROCKYLINUX_8 = "rockylinux_8"
    UBUNTU22_ML_IN_A_BOX = "ubuntu22_ml_in_a_box"
    UBUNTU24_ML_IN_A_BOX = "ubuntu24_ml_in_a_box"
    UBUNTU_20_04_X64_LTS = "ubuntu_20_04_x64_lts"
    UBUNTU_22_04_X64_LTS = "ubuntu_22_04_x64_lts"
    UBUNTU_24_04_X64_LTS = "ubuntu_24_04_x64_lts"
    WINDOWS_2022_STD = "windows_2022_std"
    WINDOWS_SERVER_2019_STD_V1 = "windows_server_2019_std_v1"


class CreateServerReinstallServersPartitionsTypedDict(TypedDict):
    size_in_gb: NotRequired[int]
    path: NotRequired[str]
    filesystem_type: NotRequired[str]


class CreateServerReinstallServersPartitions(BaseModel):
    size_in_gb: Optional[int] = None

    path: Optional[str] = None

    filesystem_type: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["size_in_gb", "path", "filesystem_type"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class CreateServerReinstallServersRaid(str, Enum):
    r"""RAID mode for the server. Set to 'raid-0' for RAID 0, 'raid-1' for RAID 1, or omit/null for no RAID configuration"""

    RAID_0 = "raid-0"
    RAID_1 = "raid-1"


class CreateServerReinstallServersAttributesTypedDict(TypedDict):
    operating_system: NotRequired[CreateServerReinstallServersOperatingSystem]
    r"""The OS selected for the reinstall process"""
    hostname: NotRequired[str]
    r"""The server hostname to set upon reinstall"""
    partitions: NotRequired[List[CreateServerReinstallServersPartitionsTypedDict]]
    ssh_keys: NotRequired[List[str]]
    r"""SSH Key IDs to set upon reinstall"""
    user_data: NotRequired[str]
    r"""User data ID to set upon reinstall"""
    raid: NotRequired[CreateServerReinstallServersRaid]
    r"""RAID mode for the server. Set to 'raid-0' for RAID 0, 'raid-1' for RAID 1, or omit/null for no RAID configuration"""
    ipxe: NotRequired[str]
    r"""URL where iPXE script is stored on, OR the iPXE script encoded in base64. This attribute is required when operating system iPXE is selected."""


class CreateServerReinstallServersAttributes(BaseModel):
    operating_system: Optional[CreateServerReinstallServersOperatingSystem] = None
    r"""The OS selected for the reinstall process"""

    hostname: Optional[str] = None
    r"""The server hostname to set upon reinstall"""

    partitions: Optional[List[CreateServerReinstallServersPartitions]] = None

    ssh_keys: Optional[List[str]] = None
    r"""SSH Key IDs to set upon reinstall"""

    user_data: Optional[str] = None
    r"""User data ID to set upon reinstall"""

    raid: Optional[CreateServerReinstallServersRaid] = None
    r"""RAID mode for the server. Set to 'raid-0' for RAID 0, 'raid-1' for RAID 1, or omit/null for no RAID configuration"""

    ipxe: Optional[str] = None
    r"""URL where iPXE script is stored on, OR the iPXE script encoded in base64. This attribute is required when operating system iPXE is selected."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "operating_system",
                "hostname",
                "partitions",
                "ssh_keys",
                "user_data",
                "raid",
                "ipxe",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class CreateServerReinstallServersDataTypedDict(TypedDict):
    type: CreateServerReinstallServersType
    attributes: NotRequired[CreateServerReinstallServersAttributesTypedDict]


class CreateServerReinstallServersData(BaseModel):
    type: CreateServerReinstallServersType

    attributes: Optional[CreateServerReinstallServersAttributes] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["attributes"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class CreateServerReinstallServersRequestBodyTypedDict(TypedDict):
    data: CreateServerReinstallServersDataTypedDict


class CreateServerReinstallServersRequestBody(BaseModel):
    data: CreateServerReinstallServersData


class CreateServerReinstallRequestTypedDict(TypedDict):
    server_id: str
    request_body: CreateServerReinstallServersRequestBodyTypedDict


class CreateServerReinstallRequest(BaseModel):
    server_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    request_body: Annotated[
        CreateServerReinstallServersRequestBody,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
