"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from latitudesh_python_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class CreateTagTagsType(str, Enum):
    TAGS = "tags"


class CreateTagTagsAttributesTypedDict(TypedDict):
    name: NotRequired[str]
    r"""Name of the Tag"""
    description: NotRequired[Nullable[str]]
    r"""Description of the Tag"""
    color: NotRequired[str]
    r"""Color of the Tag"""


class CreateTagTagsAttributes(BaseModel):
    name: Optional[str] = None
    r"""Name of the Tag"""

    description: OptionalNullable[str] = UNSET
    r"""Description of the Tag"""

    color: Optional[str] = "#ffffff"
    r"""Color of the Tag"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["name", "description", "color"])
        nullable_fields = set(["description"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class CreateTagTagsDataTypedDict(TypedDict):
    type: NotRequired[CreateTagTagsType]
    attributes: NotRequired[CreateTagTagsAttributesTypedDict]


class CreateTagTagsData(BaseModel):
    type: Optional[CreateTagTagsType] = None

    attributes: Optional[CreateTagTagsAttributes] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["type", "attributes"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class CreateTagTagsRequestBodyTypedDict(TypedDict):
    data: NotRequired[CreateTagTagsDataTypedDict]


class CreateTagTagsRequestBody(BaseModel):
    data: Optional[CreateTagTagsData] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["data"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
