"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from latitudesh_python_sdk.types import BaseModel, UNSET_SENTINEL
from latitudesh_python_sdk.utils import (
    FieldMetadata,
    PathParamMetadata,
    QueryParamMetadata,
)
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class PathParamStorageClass(str, Enum):
    r"""Backend storage tier of the access key. `standard` targets Wasabi; `high_performance` targets VAST."""

    STANDARD = "standard"
    HIGH_PERFORMANCE = "high_performance"


class DeleteStorageAccessKeysUsernameRequestTypedDict(TypedDict):
    username: str
    r"""Name of the access key to delete."""
    storage_class: PathParamStorageClass
    r"""Backend storage tier of the access key. `standard` targets Wasabi; `high_performance` targets VAST."""
    project: str
    r"""Project ID or slug the access key belongs to."""
    region: NotRequired[str]
    r"""Region slug (e.g., `DAL`, `SAO2`). Required for `high_performance` (VAST) keys to select the VAST cluster; ignored for `standard` (Wasabi) keys."""


class DeleteStorageAccessKeysUsernameRequest(BaseModel):
    username: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Name of the access key to delete."""

    storage_class: Annotated[
        PathParamStorageClass,
        FieldMetadata(path=PathParamMetadata(style="simple", explode=False)),
    ]
    r"""Backend storage tier of the access key. `standard` targets Wasabi; `high_performance` targets VAST."""

    project: Annotated[
        str, FieldMetadata(query=QueryParamMetadata(style="form", explode=True))
    ]
    r"""Project ID or slug the access key belongs to."""

    region: Annotated[
        Optional[str],
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Region slug (e.g., `DAL`, `SAO2`). Required for `high_performance` (VAST) keys to select the VAST cluster; ignored for `standard` (Wasabi) keys."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["region"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
