"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from latitudesh_python_sdk.types import BaseModel
from latitudesh_python_sdk.utils import FieldMetadata, PathParamMetadata
from typing_extensions import Annotated, TypedDict


class DeleteStorageBucketLifecycleRuleRequestTypedDict(TypedDict):
    bucket_id: str
    r"""The object storage bucket ID"""
    id: str
    r"""The lifecycle rule ID"""


class DeleteStorageBucketLifecycleRuleRequest(BaseModel):
    bucket_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""The object storage bucket ID"""

    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""The lifecycle rule ID"""
