"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from enum import Enum
from latitudesh_python_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class ElasticIPDataType(str, Enum):
    ELASTIC_IPS = "elastic_ips"


class Family(str, Enum):
    r"""The IP address family"""

    I_PV4 = "IPv4"


class Mode(str, Enum):
    r"""The routing mode for this Elastic IP"""

    ROUTED = "routed"


class Status(str, Enum):
    r"""The current status of the Elastic IP"""

    CONFIGURING = "configuring"
    ACTIVE = "active"
    MOVING = "moving"
    RELEASING = "releasing"
    ERROR = "error"


class ElasticIPDataServerTypedDict(TypedDict):
    r"""The server this Elastic IP is assigned to"""

    id: NotRequired[str]
    hostname: NotRequired[str]
    primary_ipv4: NotRequired[str]
    operating_system: NotRequired[Nullable[str]]


class ElasticIPDataServer(BaseModel):
    r"""The server this Elastic IP is assigned to"""

    id: Optional[str] = None

    hostname: Optional[str] = None

    primary_ipv4: Optional[str] = None

    operating_system: OptionalNullable[str] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["id", "hostname", "primary_ipv4", "operating_system"])
        nullable_fields = set(["operating_system"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class ElasticIPDataProjectTypedDict(TypedDict):
    r"""The project this Elastic IP belongs to"""

    id: NotRequired[str]
    name: NotRequired[str]
    slug: NotRequired[str]


class ElasticIPDataProject(BaseModel):
    r"""The project this Elastic IP belongs to"""

    id: Optional[str] = None

    name: Optional[str] = None

    slug: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["id", "name", "slug"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class LocationTypedDict(TypedDict):
    r"""The site/location within the region"""

    id: NotRequired[str]
    r"""The site ID"""
    name: NotRequired[str]
    r"""The site name"""
    slug: NotRequired[str]
    r"""The site slug"""


class Location(BaseModel):
    r"""The site/location within the region"""

    id: Optional[str] = None
    r"""The site ID"""

    name: Optional[str] = None
    r"""The site name"""

    slug: Optional[str] = None
    r"""The site slug"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["id", "name", "slug"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class ElasticIPDataRegionTypedDict(TypedDict):
    r"""The region where this Elastic IP is located"""

    id: NotRequired[str]
    r"""The region ID"""
    name: NotRequired[str]
    r"""The region name"""
    location: NotRequired[LocationTypedDict]
    r"""The site/location within the region"""


class ElasticIPDataRegion(BaseModel):
    r"""The region where this Elastic IP is located"""

    id: Optional[str] = None
    r"""The region ID"""

    name: Optional[str] = None
    r"""The region name"""

    location: Optional[Location] = None
    r"""The site/location within the region"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["id", "name", "location"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class ElasticIPDataAttributesTypedDict(TypedDict):
    address: NotRequired[str]
    r"""The IP address"""
    family: NotRequired[Family]
    r"""The IP address family"""
    prefix_length: NotRequired[int]
    r"""The prefix length (e.g., 32 for a single IP)"""
    mode: NotRequired[Mode]
    r"""The routing mode for this Elastic IP"""
    status: NotRequired[Status]
    r"""The current status of the Elastic IP"""
    created_at: NotRequired[datetime]
    r"""The timestamp when the Elastic IP was created"""
    server: NotRequired[Nullable[ElasticIPDataServerTypedDict]]
    r"""The server this Elastic IP is assigned to"""
    project: NotRequired[ElasticIPDataProjectTypedDict]
    r"""The project this Elastic IP belongs to"""
    region: NotRequired[Nullable[ElasticIPDataRegionTypedDict]]
    r"""The region where this Elastic IP is located"""


class ElasticIPDataAttributes(BaseModel):
    address: Optional[str] = None
    r"""The IP address"""

    family: Optional[Family] = None
    r"""The IP address family"""

    prefix_length: Optional[int] = None
    r"""The prefix length (e.g., 32 for a single IP)"""

    mode: Optional[Mode] = None
    r"""The routing mode for this Elastic IP"""

    status: Optional[Status] = None
    r"""The current status of the Elastic IP"""

    created_at: Optional[datetime] = None
    r"""The timestamp when the Elastic IP was created"""

    server: OptionalNullable[ElasticIPDataServer] = UNSET
    r"""The server this Elastic IP is assigned to"""

    project: Optional[ElasticIPDataProject] = None
    r"""The project this Elastic IP belongs to"""

    region: OptionalNullable[ElasticIPDataRegion] = UNSET
    r"""The region where this Elastic IP is located"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "address",
                "family",
                "prefix_length",
                "mode",
                "status",
                "created_at",
                "server",
                "project",
                "region",
            ]
        )
        nullable_fields = set(["server", "region"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class ElasticIPDataTypedDict(TypedDict):
    id: NotRequired[Nullable[str]]
    r"""The Elastic IP ID. May be null during initial provisioning."""
    type: NotRequired[ElasticIPDataType]
    attributes: NotRequired[ElasticIPDataAttributesTypedDict]


class ElasticIPData(BaseModel):
    id: OptionalNullable[str] = UNSET
    r"""The Elastic IP ID. May be null during initial provisioning."""

    type: Optional[ElasticIPDataType] = None

    attributes: Optional[ElasticIPDataAttributes] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["id", "type", "attributes"])
        nullable_fields = set(["id"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
