"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from latitudesh_python_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class EventDataType(str, Enum):
    EVENTS = "events"


class AuthorTypedDict(TypedDict):
    id: NotRequired[str]
    name: NotRequired[str]
    email: NotRequired[str]


class Author(BaseModel):
    id: Optional[str] = None

    name: Optional[str] = None

    email: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["id", "name", "email"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class EventDataProjectTypedDict(TypedDict):
    id: NotRequired[str]
    name: NotRequired[str]
    slug: NotRequired[str]


class EventDataProject(BaseModel):
    id: Optional[str] = None

    name: Optional[str] = None

    slug: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["id", "name", "slug"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class EventDataTeamTypedDict(TypedDict):
    id: NotRequired[str]
    name: NotRequired[str]


class EventDataTeam(BaseModel):
    id: Optional[str] = None

    name: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["id", "name"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class TargetTypedDict(TypedDict):
    id: NotRequired[str]
    name: NotRequired[str]


class Target(BaseModel):
    id: Optional[str] = None

    name: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["id", "name"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class PropertiesTypedDict(TypedDict):
    r"""Additional event-specific data"""


class Properties(BaseModel):
    r"""Additional event-specific data"""


class EventDataAttributesTypedDict(TypedDict):
    action: NotRequired[str]
    created_at: NotRequired[str]
    author: NotRequired[AuthorTypedDict]
    project: NotRequired[EventDataProjectTypedDict]
    team: NotRequired[EventDataTeamTypedDict]
    target: NotRequired[TargetTypedDict]
    properties: NotRequired[Nullable[PropertiesTypedDict]]
    r"""Additional event-specific data"""


class EventDataAttributes(BaseModel):
    action: Optional[str] = None

    created_at: Optional[str] = None

    author: Optional[Author] = None

    project: Optional[EventDataProject] = None

    team: Optional[EventDataTeam] = None

    target: Optional[Target] = None

    properties: OptionalNullable[Properties] = UNSET
    r"""Additional event-specific data"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "action",
                "created_at",
                "author",
                "project",
                "team",
                "target",
                "properties",
            ]
        )
        nullable_fields = set(["properties"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class EventDataTypedDict(TypedDict):
    id: NotRequired[str]
    type: NotRequired[EventDataType]
    attributes: NotRequired[EventDataAttributesTypedDict]


class EventData(BaseModel):
    id: Optional[str] = None

    type: Optional[EventDataType] = None

    attributes: Optional[EventDataAttributes] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["id", "type", "attributes"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
