"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .project_include import ProjectInclude, ProjectIncludeTypedDict
from .team_include import TeamInclude, TeamIncludeTypedDict
from datetime import datetime
from enum import Enum
from latitudesh_python_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class FilesystemDataType(str, Enum):
    FILESYSTEMS = "filesystems"


class FilesystemDataStorageClass(str, Enum):
    STANDARD = "standard"
    HIGH_PERFORMANCE = "high_performance"


class FilesystemDataAttributesTypedDict(TypedDict):
    name: NotRequired[str]
    size_in_gb: NotRequired[int]
    storage_class: NotRequired[Nullable[FilesystemDataStorageClass]]
    created_at: NotRequired[Nullable[datetime]]
    keyring: NotRequired[Nullable[str]]
    r"""Keyring secret used to mount the filesystem. Returned only for dashboard-origin requests; null until the filesystem is provisioned."""
    cluster_user: NotRequired[Nullable[str]]
    r"""Cluster user used to mount the filesystem. Returned only for dashboard-origin requests; null until the filesystem is provisioned."""
    volume_path: NotRequired[Nullable[str]]
    r"""Path of the filesystem volume inside the cluster. Returned only for dashboard-origin requests; null until the filesystem is provisioned."""
    project: NotRequired[ProjectIncludeTypedDict]
    team: NotRequired[TeamIncludeTypedDict]


class FilesystemDataAttributes(BaseModel):
    name: Optional[str] = None

    size_in_gb: Optional[int] = None

    storage_class: OptionalNullable[FilesystemDataStorageClass] = UNSET

    created_at: OptionalNullable[datetime] = UNSET

    keyring: OptionalNullable[str] = UNSET
    r"""Keyring secret used to mount the filesystem. Returned only for dashboard-origin requests; null until the filesystem is provisioned."""

    cluster_user: OptionalNullable[str] = UNSET
    r"""Cluster user used to mount the filesystem. Returned only for dashboard-origin requests; null until the filesystem is provisioned."""

    volume_path: OptionalNullable[str] = UNSET
    r"""Path of the filesystem volume inside the cluster. Returned only for dashboard-origin requests; null until the filesystem is provisioned."""

    project: Optional[ProjectInclude] = None

    team: Optional[TeamInclude] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "name",
                "size_in_gb",
                "storage_class",
                "created_at",
                "keyring",
                "cluster_user",
                "volume_path",
                "project",
                "team",
            ]
        )
        nullable_fields = set(
            ["storage_class", "created_at", "keyring", "cluster_user", "volume_path"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class FilesystemDataTypedDict(TypedDict):
    id: NotRequired[str]
    type: NotRequired[FilesystemDataType]
    attributes: NotRequired[FilesystemDataAttributesTypedDict]


class FilesystemData(BaseModel):
    id: Optional[str] = None

    type: Optional[FilesystemDataType] = None

    attributes: Optional[FilesystemDataAttributes] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["id", "type", "attributes"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
