"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from latitudesh_python_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from latitudesh_python_sdk.utils import FieldMetadata, QueryParamMetadata
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class GetStorageAccessKeysRequestTypedDict(TypedDict):
    project: str
    r"""Project ID or slug to list access keys for."""


class GetStorageAccessKeysRequest(BaseModel):
    project: Annotated[
        str, FieldMetadata(query=QueryParamMetadata(style="form", explode=True))
    ]
    r"""Project ID or slug to list access keys for."""


class StandardTypedDict(TypedDict):
    r"""Access key metadata. Exact fields depend on the storage provider."""

    name: NotRequired[str]
    username: NotRequired[str]
    access_key_id: NotRequired[str]
    status: NotRequired[str]
    created_at: NotRequired[str]
    region: NotRequired[Nullable[str]]


class Standard(BaseModel):
    r"""Access key metadata. Exact fields depend on the storage provider."""

    name: Optional[str] = None

    username: Optional[str] = None

    access_key_id: Optional[str] = None

    status: Optional[str] = None

    created_at: Optional[str] = None

    region: OptionalNullable[str] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["name", "username", "access_key_id", "status", "created_at", "region"]
        )
        nullable_fields = set(["region"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class HighPerformanceTypedDict(TypedDict):
    r"""Access key metadata. Exact fields depend on the storage provider."""

    name: NotRequired[str]
    username: NotRequired[str]
    access_key_id: NotRequired[str]
    status: NotRequired[str]
    created_at: NotRequired[str]
    region: NotRequired[str]


class HighPerformance(BaseModel):
    r"""Access key metadata. Exact fields depend on the storage provider."""

    name: Optional[str] = None

    username: Optional[str] = None

    access_key_id: Optional[str] = None

    status: Optional[str] = None

    created_at: Optional[str] = None

    region: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["name", "username", "access_key_id", "status", "created_at", "region"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class GetStorageAccessKeysDataTypedDict(TypedDict):
    r"""Access keys grouped by storage class."""

    standard: NotRequired[List[StandardTypedDict]]
    r"""Wasabi (standard) access keys."""
    high_performance: NotRequired[List[HighPerformanceTypedDict]]
    r"""VAST (high_performance) access keys, across all regions."""


class GetStorageAccessKeysData(BaseModel):
    r"""Access keys grouped by storage class."""

    standard: Optional[List[Standard]] = None
    r"""Wasabi (standard) access keys."""

    high_performance: Optional[List[HighPerformance]] = None
    r"""VAST (high_performance) access keys, across all regions."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["standard", "high_performance"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class GetStorageAccessKeysResponseBodyTypedDict(TypedDict):
    r"""Success"""

    data: NotRequired[GetStorageAccessKeysDataTypedDict]
    r"""Access keys grouped by storage class."""


class GetStorageAccessKeysResponseBody(BaseModel):
    r"""Success"""

    data: Optional[GetStorageAccessKeysData] = None
    r"""Access keys grouped by storage class."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["data"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
