"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .volume_data import VolumeData, VolumeDataTypedDict
from latitudesh_python_sdk.types import BaseModel, UNSET_SENTINEL
from latitudesh_python_sdk.utils import FieldMetadata, PathParamMetadata
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class GetStorageVolumeRequestTypedDict(TypedDict):
    id: str
    r"""The volume storage ID"""


class GetStorageVolumeRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""The volume storage ID"""


class GetStorageVolumeResponseBodyTypedDict(TypedDict):
    r"""Success"""

    data: NotRequired[VolumeDataTypedDict]


class GetStorageVolumeResponseBody(BaseModel):
    r"""Success"""

    data: Optional[VolumeData] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["data"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
