"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .object_storage_data import ObjectStorageData, ObjectStorageDataTypedDict
from latitudesh_python_sdk.types import BaseModel, UNSET_SENTINEL
from latitudesh_python_sdk.utils import FieldMetadata, PathParamMetadata
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class GetStorageObjectRequestTypedDict(TypedDict):
    id: str
    r"""The object storage ID"""


class GetStorageObjectRequest(BaseModel):
    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""The object storage ID"""


class GetStorageObjectResponseBodyTypedDict(TypedDict):
    r"""Success"""

    data: NotRequired[ObjectStorageDataTypedDict]


class GetStorageObjectResponseBody(BaseModel):
    r"""Success"""

    data: Optional[ObjectStorageData] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["data"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
