"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .lifecycle_rule_data import LifecycleRuleData, LifecycleRuleDataTypedDict
from latitudesh_python_sdk.types import BaseModel, UNSET_SENTINEL
from latitudesh_python_sdk.utils import FieldMetadata, PathParamMetadata
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class GetStorageBucketLifecycleRuleRequestTypedDict(TypedDict):
    bucket_id: str
    r"""The object storage bucket ID"""
    id: str
    r"""The lifecycle rule ID"""


class GetStorageBucketLifecycleRuleRequest(BaseModel):
    bucket_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""The object storage bucket ID"""

    id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""The lifecycle rule ID"""


class GetStorageBucketLifecycleRuleResponseBodyTypedDict(TypedDict):
    r"""Success"""

    data: NotRequired[LifecycleRuleDataTypedDict]


class GetStorageBucketLifecycleRuleResponseBody(BaseModel):
    r"""Success"""

    data: Optional[LifecycleRuleData] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["data"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
