"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from latitudesh_python_sdk.types import BaseModel, UNSET_SENTINEL
from latitudesh_python_sdk.utils import FieldMetadata, QueryParamMetadata
import pydantic
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class GetStoragePlansRequestTypedDict(TypedDict):
    filter_storage_type: NotRequired[str]
    r"""Filter by storage type (filesystem or object)"""
    filter_storage_class: NotRequired[str]
    r"""Filter by storage class (standard or high_performance)"""


class GetStoragePlansRequest(BaseModel):
    filter_storage_type: Annotated[
        Optional[str],
        pydantic.Field(alias="filter[storage_type]"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Filter by storage type (filesystem or object)"""

    filter_storage_class: Annotated[
        Optional[str],
        pydantic.Field(alias="filter[storage_class]"),
        FieldMetadata(query=QueryParamMetadata(style="form", explode=True)),
    ] = None
    r"""Filter by storage class (standard or high_performance)"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["filter[storage_type]", "filter[storage_class]"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
