"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from enum import Enum
from latitudesh_python_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class IPAddressDataType(str, Enum):
    IP_ADDRESSES = "ip_addresses"


class IPAddressDataFamily(str, Enum):
    I_PV4 = "IPv4"
    I_PV6 = "IPv6"


class IPAddressDataAttributesType(str, Enum):
    PUBLIC = "Public"
    PRIVATE = "Private"
    ELASTIC = "Elastic"


class IPAddressDataProjectTypedDict(TypedDict):
    id: NotRequired[str]
    name: NotRequired[str]


class IPAddressDataProject(BaseModel):
    id: Optional[str] = None

    name: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["id", "name"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class IPAddressDataLocationTypedDict(TypedDict):
    id: NotRequired[str]
    name: NotRequired[str]
    slug: NotRequired[str]


class IPAddressDataLocation(BaseModel):
    id: Optional[str] = None

    name: Optional[str] = None

    slug: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["id", "name", "slug"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class IPAddressDataRegionTypedDict(TypedDict):
    id: NotRequired[str]
    name: NotRequired[str]
    location: NotRequired[IPAddressDataLocationTypedDict]


class IPAddressDataRegion(BaseModel):
    id: Optional[str] = None

    name: Optional[str] = None

    location: Optional[IPAddressDataLocation] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["id", "name", "location"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class AssignmentTypedDict(TypedDict):
    r"""Server assignment information. Returns an empty object when the IP is not assigned to an active server (e.g., when the server is decommissioning or deleted)."""

    server_id: NotRequired[str]
    hostname: NotRequired[str]
    assigned_at: NotRequired[str]


class Assignment(BaseModel):
    r"""Server assignment information. Returns an empty object when the IP is not assigned to an active server (e.g., when the server is decommissioning or deleted)."""

    server_id: Optional[str] = None

    hostname: Optional[str] = None

    assigned_at: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["server_id", "hostname", "assigned_at"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class ElasticTypedDict(TypedDict):
    r"""Elastic IP details. Returns an empty object when the IP is not an Elastic IP."""

    id: NotRequired[str]
    mode: NotRequired[str]
    status: NotRequired[str]


class Elastic(BaseModel):
    r"""Elastic IP details. Returns an empty object when the IP is not an Elastic IP."""

    id: Optional[str] = None

    mode: Optional[str] = None

    status: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["id", "mode", "status"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class IPAddressDataAttributesTypedDict(TypedDict):
    address: NotRequired[str]
    cidr: NotRequired[Nullable[str]]
    family: NotRequired[IPAddressDataFamily]
    gateway: NotRequired[Nullable[str]]
    netmask: NotRequired[str]
    type: NotRequired[IPAddressDataAttributesType]
    public: NotRequired[bool]
    management: NotRequired[bool]
    additional: NotRequired[bool]
    project: NotRequired[IPAddressDataProjectTypedDict]
    region: NotRequired[IPAddressDataRegionTypedDict]
    available: NotRequired[bool]
    assignment: NotRequired[AssignmentTypedDict]
    r"""Server assignment information. Returns an empty object when the IP is not assigned to an active server (e.g., when the server is decommissioning or deleted)."""
    elastic: NotRequired[ElasticTypedDict]
    r"""Elastic IP details. Returns an empty object when the IP is not an Elastic IP."""
    created_at: NotRequired[Nullable[datetime]]


class IPAddressDataAttributes(BaseModel):
    address: Optional[str] = None

    cidr: OptionalNullable[str] = UNSET

    family: Optional[IPAddressDataFamily] = None

    gateway: OptionalNullable[str] = UNSET

    netmask: Optional[str] = None

    type: Optional[IPAddressDataAttributesType] = None

    public: Optional[bool] = None

    management: Optional[bool] = None

    additional: Optional[bool] = None

    project: Optional[IPAddressDataProject] = None

    region: Optional[IPAddressDataRegion] = None

    available: Optional[bool] = None

    assignment: Optional[Assignment] = None
    r"""Server assignment information. Returns an empty object when the IP is not assigned to an active server (e.g., when the server is decommissioning or deleted)."""

    elastic: Optional[Elastic] = None
    r"""Elastic IP details. Returns an empty object when the IP is not an Elastic IP."""

    created_at: OptionalNullable[datetime] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "address",
                "cidr",
                "family",
                "gateway",
                "netmask",
                "type",
                "public",
                "management",
                "additional",
                "project",
                "region",
                "available",
                "assignment",
                "elastic",
                "created_at",
            ]
        )
        nullable_fields = set(["cidr", "gateway", "created_at"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class IPAddressDataTypedDict(TypedDict):
    id: NotRequired[str]
    type: NotRequired[IPAddressDataType]
    attributes: NotRequired[IPAddressDataAttributesTypedDict]


class IPAddressData(BaseModel):
    id: Optional[str] = None

    type: Optional[IPAddressDataType] = None

    attributes: Optional[IPAddressDataAttributes] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["id", "type", "attributes"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
