"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .ip_address_data import IPAddressData, IPAddressDataTypedDict
from latitudesh_python_sdk.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class IPAddressMetaTypedDict(TypedDict):
    pass


class IPAddressMeta(BaseModel):
    pass


class IPAddressTypedDict(TypedDict):
    data: NotRequired[IPAddressDataTypedDict]
    meta: NotRequired[IPAddressMetaTypedDict]


class IPAddress(BaseModel):
    data: Optional[IPAddressData] = None

    meta: Optional[IPAddressMeta] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["data", "meta"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
