"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from latitudesh_python_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class KubernetesClusterUpdateResponseType(str, Enum):
    KUBERNETES_CLUSTERS = "kubernetes_clusters"


class KubernetesClusterUpdateResponseStatus(str, Enum):
    r"""The update status. 'scaling' indicates nodes are being added or removed. 'unchanged' indicates the requested count matches the current count."""

    SCALING = "scaling"
    UNCHANGED = "unchanged"


class KubernetesClusterUpdateResponseAttributesTypedDict(TypedDict):
    name: NotRequired[str]
    r"""The cluster name"""
    status: NotRequired[KubernetesClusterUpdateResponseStatus]
    r"""The update status. 'scaling' indicates nodes are being added or removed. 'unchanged' indicates the requested count matches the current count."""
    worker_count: NotRequired[Nullable[int]]
    r"""The requested number of worker nodes. Present when scaling workers."""
    control_plane_count: NotRequired[Nullable[int]]
    r"""The requested number of control plane nodes. Present when scaling control plane."""


class KubernetesClusterUpdateResponseAttributes(BaseModel):
    name: Optional[str] = None
    r"""The cluster name"""

    status: Optional[KubernetesClusterUpdateResponseStatus] = None
    r"""The update status. 'scaling' indicates nodes are being added or removed. 'unchanged' indicates the requested count matches the current count."""

    worker_count: OptionalNullable[int] = UNSET
    r"""The requested number of worker nodes. Present when scaling workers."""

    control_plane_count: OptionalNullable[int] = UNSET
    r"""The requested number of control plane nodes. Present when scaling control plane."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["name", "status", "worker_count", "control_plane_count"])
        nullable_fields = set(["worker_count", "control_plane_count"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class KubernetesClusterUpdateResponseDataTypedDict(TypedDict):
    type: NotRequired[KubernetesClusterUpdateResponseType]
    id: NotRequired[str]
    r"""The cluster ID (format: kc_<hash>)"""
    attributes: NotRequired[KubernetesClusterUpdateResponseAttributesTypedDict]


class KubernetesClusterUpdateResponseData(BaseModel):
    type: Optional[KubernetesClusterUpdateResponseType] = None

    id: Optional[str] = None
    r"""The cluster ID (format: kc_<hash>)"""

    attributes: Optional[KubernetesClusterUpdateResponseAttributes] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["type", "id", "attributes"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class KubernetesClusterUpdateResponseTypedDict(TypedDict):
    data: NotRequired[KubernetesClusterUpdateResponseDataTypedDict]


class KubernetesClusterUpdateResponse(BaseModel):
    data: Optional[KubernetesClusterUpdateResponseData] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["data"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
