"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from latitudesh_python_sdk.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class KubernetesClusterKubeconfigAttributesTypedDict(TypedDict):
    cluster_name: NotRequired[str]
    r"""The cluster name"""
    kubeconfig: NotRequired[str]
    r"""The kubeconfig YAML content for connecting to the cluster"""


class KubernetesClusterKubeconfigAttributes(BaseModel):
    cluster_name: Optional[str] = None
    r"""The cluster name"""

    kubeconfig: Optional[str] = None
    r"""The kubeconfig YAML content for connecting to the cluster"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["cluster_name", "kubeconfig"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class KubernetesClusterKubeconfigDataTypedDict(TypedDict):
    id: NotRequired[str]
    r"""The cluster name"""
    type: NotRequired[str]
    attributes: NotRequired[KubernetesClusterKubeconfigAttributesTypedDict]


class KubernetesClusterKubeconfigData(BaseModel):
    id: Optional[str] = None
    r"""The cluster name"""

    type: Optional[str] = None

    attributes: Optional[KubernetesClusterKubeconfigAttributes] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["id", "type", "attributes"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class KubernetesClusterKubeconfigTypedDict(TypedDict):
    data: NotRequired[KubernetesClusterKubeconfigDataTypedDict]


class KubernetesClusterKubeconfig(BaseModel):
    data: Optional[KubernetesClusterKubeconfigData] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["data"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
