"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .kubernetes_cluster_summary_data import (
    KubernetesClusterSummaryData,
    KubernetesClusterSummaryDataTypedDict,
)
from latitudesh_python_sdk.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class KubernetesClustersTypedDict(TypedDict):
    r"""Response schema for listing clusters (uses summary representation)"""

    data: NotRequired[List[KubernetesClusterSummaryDataTypedDict]]


class KubernetesClusters(BaseModel):
    r"""Response schema for listing clusters (uses summary representation)"""

    data: Optional[List[KubernetesClusterSummaryData]] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["data"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
