"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from latitudesh_python_sdk.types import BaseModel
from latitudesh_python_sdk.utils import FieldMetadata, QueryParamMetadata
from typing_extensions import Annotated, TypedDict


class ListLksClustersRequestTypedDict(TypedDict):
    project_id: str
    r"""Project `id_hash` or slug. Required — clusters are always scoped to a project."""


class ListLksClustersRequest(BaseModel):
    project_id: Annotated[
        str, FieldMetadata(query=QueryParamMetadata(style="form", explode=True))
    ]
    r"""Project `id_hash` or slug. Required — clusters are always scoped to a project."""
