"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from latitudesh_python_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class LksClusterDataType(str, Enum):
    LKS_CLUSTERS = "lks_clusters"


class NetworkTypedDict(TypedDict):
    r"""Configured cluster CIDRs. Always present: the ranges are columns on the cluster with platform defaults."""

    pod_cidrs: NotRequired[List[str]]
    service_cidrs: NotRequired[List[str]]
    node_cidrs: NotRequired[List[str]]


class Network(BaseModel):
    r"""Configured cluster CIDRs. Always present: the ranges are columns on the cluster with platform defaults."""

    pod_cidrs: Optional[List[str]] = None

    service_cidrs: Optional[List[str]] = None

    node_cidrs: Optional[List[str]] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["pod_cidrs", "service_cidrs", "node_cidrs"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class LksClusterDataAttributesTypedDict(TypedDict):
    name: NotRequired[str]
    description: NotRequired[Nullable[str]]
    project_id: NotRequired[Nullable[str]]
    site: NotRequired[Nullable[str]]
    status: NotRequired[Nullable[str]]
    r"""Lifecycle state (open enum, sourced from NetBox/controller)"""
    message: NotRequired[Nullable[str]]
    reason: NotRequired[Nullable[str]]
    r"""Machine-readable status reason (open enum)"""
    control_plane_endpoint: NotRequired[Nullable[str]]
    kubeconfig_url: NotRequired[Nullable[str]]
    kubernetes_version: NotRequired[Nullable[str]]
    platform_version: NotRequired[Nullable[str]]
    network: NotRequired[NetworkTypedDict]
    r"""Configured cluster CIDRs. Always present: the ranges are columns on the cluster with platform defaults."""
    created_at: NotRequired[Nullable[str]]
    updated_at: NotRequired[Nullable[str]]


class LksClusterDataAttributes(BaseModel):
    name: Optional[str] = None

    description: OptionalNullable[str] = UNSET

    project_id: OptionalNullable[str] = UNSET

    site: OptionalNullable[str] = UNSET

    status: OptionalNullable[str] = UNSET
    r"""Lifecycle state (open enum, sourced from NetBox/controller)"""

    message: OptionalNullable[str] = UNSET

    reason: OptionalNullable[str] = UNSET
    r"""Machine-readable status reason (open enum)"""

    control_plane_endpoint: OptionalNullable[str] = UNSET

    kubeconfig_url: OptionalNullable[str] = UNSET

    kubernetes_version: OptionalNullable[str] = UNSET

    platform_version: OptionalNullable[str] = UNSET

    network: Optional[Network] = None
    r"""Configured cluster CIDRs. Always present: the ranges are columns on the cluster with platform defaults."""

    created_at: OptionalNullable[str] = UNSET

    updated_at: OptionalNullable[str] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "name",
                "description",
                "project_id",
                "site",
                "status",
                "message",
                "reason",
                "control_plane_endpoint",
                "kubeconfig_url",
                "kubernetes_version",
                "platform_version",
                "network",
                "created_at",
                "updated_at",
            ]
        )
        nullable_fields = set(
            [
                "description",
                "project_id",
                "site",
                "status",
                "message",
                "reason",
                "control_plane_endpoint",
                "kubeconfig_url",
                "kubernetes_version",
                "platform_version",
                "created_at",
                "updated_at",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class LksClusterDataTypedDict(TypedDict):
    id: NotRequired[str]
    type: NotRequired[LksClusterDataType]
    attributes: NotRequired[LksClusterDataAttributesTypedDict]


class LksClusterData(BaseModel):
    id: Optional[str] = None

    type: Optional[LksClusterDataType] = None

    attributes: Optional[LksClusterDataAttributes] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["id", "type", "attributes"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
