"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from latitudesh_python_sdk.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class LksKubernetesVersionDataType(str, Enum):
    LKS_KUBERNETES_VERSIONS = "lks_kubernetes_versions"


class LksKubernetesVersionDataAttributesTypedDict(TypedDict):
    version: NotRequired[str]
    default: NotRequired[bool]
    available_for_creation: NotRequired[bool]
    available_for_upgrade: NotRequired[bool]


class LksKubernetesVersionDataAttributes(BaseModel):
    version: Optional[str] = None

    default: Optional[bool] = None

    available_for_creation: Optional[bool] = None

    available_for_upgrade: Optional[bool] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["version", "default", "available_for_creation", "available_for_upgrade"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class LksKubernetesVersionDataTypedDict(TypedDict):
    id: NotRequired[str]
    type: NotRequired[LksKubernetesVersionDataType]
    attributes: NotRequired[LksKubernetesVersionDataAttributesTypedDict]


class LksKubernetesVersionData(BaseModel):
    id: Optional[str] = None

    type: Optional[LksKubernetesVersionDataType] = None

    attributes: Optional[LksKubernetesVersionDataAttributes] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["id", "type", "attributes"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
