"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from latitudesh_python_sdk.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class OperatingSystemDataType(str, Enum):
    OPERATING_SYSTEMS = "operating_systems"


class FeaturesTypedDict(TypedDict):
    raid: NotRequired[bool]
    ssh_keys: NotRequired[bool]
    user_data: NotRequired[bool]


class Features(BaseModel):
    raid: Optional[bool] = None

    ssh_keys: Optional[bool] = None

    user_data: Optional[bool] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["raid", "ssh_keys", "user_data"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class OperatingSystemDataAttributesTypedDict(TypedDict):
    features: NotRequired[FeaturesTypedDict]
    name: NotRequired[str]
    slug: NotRequired[str]
    distro: NotRequired[str]
    user: NotRequired[str]
    version: NotRequired[str]
    provisionable_on: NotRequired[List[str]]


class OperatingSystemDataAttributes(BaseModel):
    features: Optional[Features] = None

    name: Optional[str] = None

    slug: Optional[str] = None

    distro: Optional[str] = None

    user: Optional[str] = None

    version: Optional[str] = None

    provisionable_on: Optional[List[str]] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "features",
                "name",
                "slug",
                "distro",
                "user",
                "version",
                "provisionable_on",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class OperatingSystemDataTypedDict(TypedDict):
    id: NotRequired[str]
    type: NotRequired[OperatingSystemDataType]
    attributes: NotRequired[OperatingSystemDataAttributesTypedDict]


class OperatingSystemData(BaseModel):
    id: Optional[str] = None

    type: Optional[OperatingSystemDataType] = None

    attributes: Optional[OperatingSystemDataAttributes] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["id", "type", "attributes"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
