"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .team import Team, TeamTypedDict
from enum import Enum
from latitudesh_python_sdk.types import BaseModel
from latitudesh_python_sdk.utils import (
    FieldMetadata,
    PathParamMetadata,
    RequestMetadata,
)
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class PatchCurrentTeamType(str, Enum):
    TEAMS = "teams"


class PatchCurrentTeamCurrency(str, Enum):
    USD = "USD"
    BRL = "BRL"


class PatchCurrentTeamAttributesTypedDict(TypedDict):
    address: NotRequired[str]
    name: NotRequired[str]
    currency: NotRequired[PatchCurrentTeamCurrency]
    referred_code: NotRequired[str]


class PatchCurrentTeamAttributes(BaseModel):
    address: Optional[str] = None

    name: Optional[str] = None

    currency: Optional[PatchCurrentTeamCurrency] = PatchCurrentTeamCurrency.USD

    referred_code: Optional[str] = None


class PatchCurrentTeamDataTypedDict(TypedDict):
    id: str
    type: PatchCurrentTeamType
    attributes: NotRequired[PatchCurrentTeamAttributesTypedDict]


class PatchCurrentTeamData(BaseModel):
    id: str

    type: PatchCurrentTeamType

    attributes: Optional[PatchCurrentTeamAttributes] = None


class PatchCurrentTeamRequestBodyTypedDict(TypedDict):
    data: PatchCurrentTeamDataTypedDict


class PatchCurrentTeamRequestBody(BaseModel):
    data: PatchCurrentTeamData


class PatchCurrentTeamRequestTypedDict(TypedDict):
    team_id: str
    request_body: NotRequired[PatchCurrentTeamRequestBodyTypedDict]


class PatchCurrentTeamRequest(BaseModel):
    team_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    request_body: Annotated[
        Optional[PatchCurrentTeamRequestBody],
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ] = None


class PatchCurrentTeamResponseBodyTypedDict(TypedDict):
    r"""Success"""

    data: NotRequired[TeamTypedDict]


class PatchCurrentTeamResponseBody(BaseModel):
    r"""Success"""

    data: Optional[Team] = None
