"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .api_key import APIKey, APIKeyTypedDict
from .update_api_key import UpdateAPIKey, UpdateAPIKeyTypedDict
from latitudesh_python_sdk.types import BaseModel
from latitudesh_python_sdk.utils import (
    FieldMetadata,
    PathParamMetadata,
    RequestMetadata,
)
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class PatchAPIKeyRequestTypedDict(TypedDict):
    api_key_id: str
    update_api_key: UpdateAPIKeyTypedDict


class PatchAPIKeyRequest(BaseModel):
    api_key_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    update_api_key: Annotated[
        UpdateAPIKey,
        FieldMetadata(request=RequestMetadata(media_type="application/vnd.api+json")),
    ]


class PatchAPIKeyResponseBodyTypedDict(TypedDict):
    r"""Success"""

    data: NotRequired[APIKeyTypedDict]


class PatchAPIKeyResponseBody(BaseModel):
    r"""Success"""

    data: Optional[APIKey] = None
