"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from latitudesh_python_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
import pydantic
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class PlanDataType(str, Enum):
    PLANS = "plans"


class PlanDataFeatures(str, Enum):
    SSH = "ssh"
    RAID = "raid"
    USER_DATA = "user_data"
    SEV = "sev"


class CPUTypedDict(TypedDict):
    type: NotRequired[str]
    clock: NotRequired[float]
    cores: NotRequired[float]
    count: NotRequired[float]


class CPU(BaseModel):
    type: Optional[str] = None

    clock: Optional[float] = None

    cores: Optional[float] = None

    count: Optional[float] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["type", "clock", "cores", "count"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class MemoryTypedDict(TypedDict):
    total: NotRequired[float]


class Memory(BaseModel):
    total: Optional[float] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["total"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class PlanDataAttributesType(str, Enum):
    SSD = "SSD"
    HDD = "HDD"
    NVME = "NVME"


class DrivesTypedDict(TypedDict):
    count: NotRequired[float]
    size: NotRequired[str]
    type: NotRequired[PlanDataAttributesType]


class Drives(BaseModel):
    count: Optional[float] = None

    size: Optional[str] = None

    type: Optional[PlanDataAttributesType] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["count", "size", "type"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class NicsTypedDict(TypedDict):
    count: NotRequired[float]
    type: NotRequired[str]


class Nics(BaseModel):
    count: Optional[float] = None

    type: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["count", "type"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class GpuTypedDict(TypedDict):
    count: NotRequired[float]
    type: NotRequired[str]
    vram_per_gpu: NotRequired[Nullable[float]]
    r"""VRAM per GPU in GB"""
    interconnect: NotRequired[Nullable[str]]
    r"""GPU interconnection type (e.g., NVLink, PCIe)"""


class Gpu(BaseModel):
    count: Optional[float] = None

    type: Optional[str] = None

    vram_per_gpu: OptionalNullable[float] = UNSET
    r"""VRAM per GPU in GB"""

    interconnect: OptionalNullable[str] = UNSET
    r"""GPU interconnection type (e.g., NVLink, PCIe)"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["count", "type", "vram_per_gpu", "interconnect"])
        nullable_fields = set(["vram_per_gpu", "interconnect"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class SpecsTypedDict(TypedDict):
    cpu: NotRequired[CPUTypedDict]
    memory: NotRequired[MemoryTypedDict]
    drives: NotRequired[List[DrivesTypedDict]]
    nics: NotRequired[List[NicsTypedDict]]
    gpu: NotRequired[GpuTypedDict]


class Specs(BaseModel):
    cpu: Optional[CPU] = None

    memory: Optional[Memory] = None

    drives: Optional[List[Drives]] = None

    nics: Optional[List[Nics]] = None

    gpu: Optional[Gpu] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["cpu", "memory", "drives", "nics", "gpu"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class LocationsTypedDict(TypedDict):
    available: NotRequired[List[str]]
    in_stock: NotRequired[List[str]]


class Locations(BaseModel):
    available: Optional[List[str]] = None

    in_stock: Optional[List[str]] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["available", "in_stock"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class StockLevel(str, Enum):
    UNAVAILABLE = "unavailable"
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"


class PlanDataUSDTypedDict(TypedDict):
    hour: NotRequired[float]
    month: NotRequired[float]
    year: NotRequired[float]


class PlanDataUSD(BaseModel):
    hour: Optional[float] = None

    month: Optional[float] = None

    year: Optional[float] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["hour", "month", "year"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class PlanDataBRLTypedDict(TypedDict):
    hour: NotRequired[float]
    month: NotRequired[float]
    year: NotRequired[float]


class PlanDataBRL(BaseModel):
    hour: Optional[float] = None

    month: Optional[float] = None

    year: Optional[float] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["hour", "month", "year"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class PlanDataPricingTypedDict(TypedDict):
    usd: NotRequired[PlanDataUSDTypedDict]
    brl: NotRequired[PlanDataBRLTypedDict]


class PlanDataPricing(BaseModel):
    usd: Annotated[Optional[PlanDataUSD], pydantic.Field(alias="USD")] = None

    brl: Annotated[Optional[PlanDataBRL], pydantic.Field(alias="BRL")] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["USD", "BRL"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class PlanDataRegionsTypedDict(TypedDict):
    name: NotRequired[str]
    deploys_instantly: NotRequired[List[str]]
    locations: NotRequired[LocationsTypedDict]
    stock_level: NotRequired[StockLevel]
    pricing: NotRequired[PlanDataPricingTypedDict]


class PlanDataRegions(BaseModel):
    name: Optional[str] = None

    deploys_instantly: Optional[List[str]] = None

    locations: Optional[Locations] = None

    stock_level: Optional[StockLevel] = None

    pricing: Optional[PlanDataPricing] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["name", "deploys_instantly", "locations", "stock_level", "pricing"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class PlanDataAttributesTypedDict(TypedDict):
    slug: NotRequired[str]
    name: NotRequired[str]
    features: NotRequired[List[PlanDataFeatures]]
    r"""List of available features for the plan"""
    specs: NotRequired[SpecsTypedDict]
    regions: NotRequired[List[PlanDataRegionsTypedDict]]


class PlanDataAttributes(BaseModel):
    slug: Optional[str] = None

    name: Optional[str] = None

    features: Optional[List[PlanDataFeatures]] = None
    r"""List of available features for the plan"""

    specs: Optional[Specs] = None

    regions: Optional[List[PlanDataRegions]] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["slug", "name", "features", "specs", "regions"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class PlanDataTypedDict(TypedDict):
    id: NotRequired[str]
    type: NotRequired[PlanDataType]
    attributes: NotRequired[PlanDataAttributesTypedDict]


class PlanData(BaseModel):
    id: Optional[str] = None

    type: Optional[PlanDataType] = None

    attributes: Optional[PlanDataAttributes] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["id", "type", "attributes"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
