"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .plan_data import PlanData, PlanDataTypedDict
from latitudesh_python_sdk.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class PlanMetaTypedDict(TypedDict):
    pass


class PlanMeta(BaseModel):
    pass


class PlanTypedDict(TypedDict):
    data: NotRequired[PlanDataTypedDict]
    meta: NotRequired[PlanMetaTypedDict]


class Plan(BaseModel):
    data: Optional[PlanData] = None

    meta: Optional[PlanMeta] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["data", "meta"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
