"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .filesystem_data import FilesystemData, FilesystemDataTypedDict
from enum import Enum
from latitudesh_python_sdk.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class PostStorageFilesystemsFilesystemStorageType(str, Enum):
    FILESYSTEMS = "filesystems"


class PostStorageFilesystemsFilesystemStorageAttributesTypedDict(TypedDict):
    project: str
    r"""Project ID or slug"""
    name: str
    r"""Filesystem name"""
    size_in_gb: NotRequired[int]
    r"""Size in GB (not required, default is 1500)"""


class PostStorageFilesystemsFilesystemStorageAttributes(BaseModel):
    project: str
    r"""Project ID or slug"""

    name: str
    r"""Filesystem name"""

    size_in_gb: Optional[int] = 1500
    r"""Size in GB (not required, default is 1500)"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["size_in_gb"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class PostStorageFilesystemsFilesystemStorageDataTypedDict(TypedDict):
    type: PostStorageFilesystemsFilesystemStorageType
    attributes: PostStorageFilesystemsFilesystemStorageAttributesTypedDict


class PostStorageFilesystemsFilesystemStorageData(BaseModel):
    type: PostStorageFilesystemsFilesystemStorageType

    attributes: PostStorageFilesystemsFilesystemStorageAttributes


class PostStorageFilesystemsFilesystemStorageRequestBodyTypedDict(TypedDict):
    data: PostStorageFilesystemsFilesystemStorageDataTypedDict


class PostStorageFilesystemsFilesystemStorageRequestBody(BaseModel):
    data: PostStorageFilesystemsFilesystemStorageData


class PostStorageFilesystemsResponseBodyTypedDict(TypedDict):
    r"""Created"""

    data: NotRequired[FilesystemDataTypedDict]


class PostStorageFilesystemsResponseBody(BaseModel):
    r"""Created"""

    data: Optional[FilesystemData] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["data"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
