"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .ssh_key_data import SSHKeyData, SSHKeyDataTypedDict
from enum import Enum
from latitudesh_python_sdk.types import BaseModel, UNSET_SENTINEL
from latitudesh_python_sdk.utils import (
    FieldMetadata,
    PathParamMetadata,
    RequestMetadata,
)
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class PostProjectSSHKeySSHKeysType(str, Enum):
    SSH_KEYS = "ssh_keys"


class PostProjectSSHKeySSHKeysAttributesTypedDict(TypedDict):
    name: NotRequired[str]
    r"""Name of the SSH Key"""
    public_key: NotRequired[str]
    r"""SSH Public Key"""


class PostProjectSSHKeySSHKeysAttributes(BaseModel):
    name: Optional[str] = None
    r"""Name of the SSH Key"""

    public_key: Optional[str] = None
    r"""SSH Public Key"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["name", "public_key"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class PostProjectSSHKeySSHKeysDataTypedDict(TypedDict):
    type: PostProjectSSHKeySSHKeysType
    attributes: NotRequired[PostProjectSSHKeySSHKeysAttributesTypedDict]


class PostProjectSSHKeySSHKeysData(BaseModel):
    type: PostProjectSSHKeySSHKeysType

    attributes: Optional[PostProjectSSHKeySSHKeysAttributes] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["attributes"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class PostProjectSSHKeySSHKeysRequestBodyTypedDict(TypedDict):
    data: PostProjectSSHKeySSHKeysDataTypedDict


class PostProjectSSHKeySSHKeysRequestBody(BaseModel):
    data: PostProjectSSHKeySSHKeysData


class PostProjectSSHKeyRequestTypedDict(TypedDict):
    project_id: str
    r"""Project ID or Slug"""
    request_body: PostProjectSSHKeySSHKeysRequestBodyTypedDict


class PostProjectSSHKeyRequest(BaseModel):
    project_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Project ID or Slug"""

    request_body: Annotated[
        PostProjectSSHKeySSHKeysRequestBody,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]


class PostProjectSSHKeyResponseBodyTypedDict(TypedDict):
    r"""Created"""

    data: NotRequired[SSHKeyDataTypedDict]


class PostProjectSSHKeyResponseBody(BaseModel):
    r"""Created"""

    data: Optional[SSHKeyData] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["data"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
