"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from latitudesh_python_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class BillingModelTypedDict(TypedDict):
    subscription_id: NotRequired[Nullable[str]]
    type: NotRequired[str]
    method: NotRequired[str]


class BillingModel(BaseModel):
    subscription_id: OptionalNullable[str] = UNSET

    type: Optional[str] = None

    method: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["subscription_id", "type", "method"])
        nullable_fields = set(["subscription_id"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class StatsTypedDict(TypedDict):
    ip_addresses: NotRequired[int]
    prefixes: NotRequired[int]
    servers: NotRequired[int]
    vlans: NotRequired[int]


class Stats(BaseModel):
    ip_addresses: Optional[int] = None

    prefixes: Optional[int] = None

    servers: Optional[int] = None

    vlans: Optional[int] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["ip_addresses", "prefixes", "servers", "vlans"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class ProjectIncludeTypedDict(TypedDict):
    id: NotRequired[str]
    name: NotRequired[str]
    slug: NotRequired[str]
    description: NotRequired[Nullable[str]]
    billing_type: NotRequired[Nullable[str]]
    provisioning_type: NotRequired[Nullable[str]]
    billing_method: NotRequired[Nullable[str]]
    bandwidth_alert: NotRequired[bool]
    environment: NotRequired[Nullable[str]]
    billing: NotRequired[BillingModelTypedDict]
    stats: NotRequired[StatsTypedDict]


class ProjectInclude(BaseModel):
    id: Optional[str] = None

    name: Optional[str] = None

    slug: Optional[str] = None

    description: OptionalNullable[str] = UNSET

    billing_type: OptionalNullable[str] = UNSET

    provisioning_type: OptionalNullable[str] = UNSET

    billing_method: OptionalNullable[str] = UNSET

    bandwidth_alert: Optional[bool] = None

    environment: OptionalNullable[str] = UNSET

    billing: Optional[BillingModel] = None

    stats: Optional[Stats] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "id",
                "name",
                "slug",
                "description",
                "billing_type",
                "provisioning_type",
                "billing_method",
                "bandwidth_alert",
                "environment",
                "billing",
                "stats",
            ]
        )
        nullable_fields = set(
            [
                "description",
                "billing_type",
                "provisioning_type",
                "billing_method",
                "environment",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m
