"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from enum import Enum
from latitudesh_python_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class PublicNetworkDataType(str, Enum):
    PUBLIC_NETWORKS = "public_networks"


class Size(int, Enum):
    r"""IPv4 prefix length. Determines how many servers the public network can host."""

    TWENTY_SIX = 26
    TWENTY_SEVEN = 27
    TWENTY_EIGHT = 28
    TWENTY_NINE = 29


class PublicNetworkDataRole(str, Enum):
    r"""gateway: reserved for the network gateway; server: a server on the network; elastic_ip: an elastic IP; reserved: held in IPAM but not by a server; available: free to use"""

    GATEWAY = "gateway"
    SERVER = "server"
    ELASTIC_IP = "elastic_ip"
    RESERVED = "reserved"
    AVAILABLE = "available"


class PublicNetworkDataAttributesType(str, Enum):
    SERVER = "server"
    ELASTIC_IP = "elastic_ip"


class PublicNetworkDataAssignmentTypedDict(TypedDict):
    r"""The resource holding the address, when it is a server or an elastic IP"""

    type: NotRequired[PublicNetworkDataAttributesType]
    id: NotRequired[str]
    hostname: NotRequired[Nullable[str]]
    r"""Servers only"""


class PublicNetworkDataAssignment(BaseModel):
    r"""The resource holding the address, when it is a server or an elastic IP"""

    type: Optional[PublicNetworkDataAttributesType] = None

    id: Optional[str] = None

    hostname: OptionalNullable[str] = UNSET
    r"""Servers only"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["type", "id", "hostname"])
        nullable_fields = set(["hostname"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class IpsTypedDict(TypedDict):
    address: NotRequired[str]
    role: NotRequired[PublicNetworkDataRole]
    r"""gateway: reserved for the network gateway; server: a server on the network; elastic_ip: an elastic IP; reserved: held in IPAM but not by a server; available: free to use"""
    assignment: NotRequired[Nullable[PublicNetworkDataAssignmentTypedDict]]
    r"""The resource holding the address, when it is a server or an elastic IP"""


class Ips(BaseModel):
    address: Optional[str] = None

    role: Optional[PublicNetworkDataRole] = None
    r"""gateway: reserved for the network gateway; server: a server on the network; elastic_ip: an elastic IP; reserved: held in IPAM but not by a server; available: free to use"""

    assignment: OptionalNullable[PublicNetworkDataAssignment] = UNSET
    r"""The resource holding the address, when it is a server or an elastic IP"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["address", "role", "assignment"])
        nullable_fields = set(["assignment"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class PublicNetworkDataProjectTypedDict(TypedDict):
    id: NotRequired[str]
    name: NotRequired[str]
    slug: NotRequired[str]


class PublicNetworkDataProject(BaseModel):
    id: Optional[str] = None

    name: Optional[str] = None

    slug: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["id", "name", "slug"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class PublicNetworkDataLocationTypedDict(TypedDict):
    id: NotRequired[str]
    name: NotRequired[str]
    slug: NotRequired[str]


class PublicNetworkDataLocation(BaseModel):
    id: Optional[str] = None

    name: Optional[str] = None

    slug: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["id", "name", "slug"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class PublicNetworkDataRegionTypedDict(TypedDict):
    id: NotRequired[str]
    name: NotRequired[str]
    location: NotRequired[PublicNetworkDataLocationTypedDict]


class PublicNetworkDataRegion(BaseModel):
    id: Optional[str] = None

    name: Optional[str] = None

    location: Optional[PublicNetworkDataLocation] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["id", "name", "location"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class PublicNetworkDataAttributesTypedDict(TypedDict):
    ipv4: NotRequired[str]
    r"""The IPv4 network in CIDR notation (e.g., \"203.0.113.0/27\")"""
    ipv6: NotRequired[Nullable[str]]
    r"""The paired IPv6 /64 in CIDR notation (e.g., \"2001:db8:1234::/64\")"""
    size: NotRequired[Size]
    r"""IPv4 prefix length. Determines how many servers the public network can host."""
    activated: NotRequired[bool]
    r"""True once a server has been added to the public network and the public network is ready to use."""
    capacity: NotRequired[int]
    r"""Servers this public network can host"""
    ips_used: NotRequired[int]
    ips_free: NotRequired[int]
    ips: NotRequired[List[IpsTypedDict]]
    r"""Every host address of the IPv4 network and what holds it. Only returned when retrieving a single public network."""
    created_at: NotRequired[datetime]
    project: NotRequired[Nullable[PublicNetworkDataProjectTypedDict]]
    region: NotRequired[Nullable[PublicNetworkDataRegionTypedDict]]


class PublicNetworkDataAttributes(BaseModel):
    ipv4: Optional[str] = None
    r"""The IPv4 network in CIDR notation (e.g., \"203.0.113.0/27\")"""

    ipv6: OptionalNullable[str] = UNSET
    r"""The paired IPv6 /64 in CIDR notation (e.g., \"2001:db8:1234::/64\")"""

    size: Optional[Size] = None
    r"""IPv4 prefix length. Determines how many servers the public network can host."""

    activated: Optional[bool] = None
    r"""True once a server has been added to the public network and the public network is ready to use."""

    capacity: Optional[int] = None
    r"""Servers this public network can host"""

    ips_used: Optional[int] = None

    ips_free: Optional[int] = None

    ips: Optional[List[Ips]] = None
    r"""Every host address of the IPv4 network and what holds it. Only returned when retrieving a single public network."""

    created_at: Optional[datetime] = None

    project: OptionalNullable[PublicNetworkDataProject] = UNSET

    region: OptionalNullable[PublicNetworkDataRegion] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "ipv4",
                "ipv6",
                "size",
                "activated",
                "capacity",
                "ips_used",
                "ips_free",
                "ips",
                "created_at",
                "project",
                "region",
            ]
        )
        nullable_fields = set(["ipv6", "project", "region"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class PublicNetworkDataTypedDict(TypedDict):
    id: NotRequired[str]
    type: NotRequired[PublicNetworkDataType]
    attributes: NotRequired[PublicNetworkDataAttributesTypedDict]


class PublicNetworkData(BaseModel):
    id: Optional[str] = None

    type: Optional[PublicNetworkDataType] = None

    attributes: Optional[PublicNetworkDataAttributes] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["id", "type", "attributes"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
