"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from latitudesh_python_sdk.types import BaseModel
from latitudesh_python_sdk.utils import (
    FieldMetadata,
    PathParamMetadata,
    RequestMetadata,
)
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class PutProjectUserDataType(str, Enum):
    USER_DATA = "user_data"


class PutProjectUserDataAttributesTypedDict(TypedDict):
    description: NotRequired[str]
    r"""description dummy user data"""
    content: NotRequired[str]
    r"""encoded content of the User Data"""


class PutProjectUserDataAttributes(BaseModel):
    description: Optional[str] = None
    r"""description dummy user data"""

    content: Optional[str] = None
    r"""encoded content of the User Data"""


class PutProjectUserDataDataTypedDict(TypedDict):
    id: str
    type: PutProjectUserDataType
    attributes: NotRequired[PutProjectUserDataAttributesTypedDict]


class PutProjectUserDataData(BaseModel):
    id: str

    type: PutProjectUserDataType

    attributes: Optional[PutProjectUserDataAttributes] = None


class PutProjectUserDataRequestBodyTypedDict(TypedDict):
    data: PutProjectUserDataDataTypedDict


class PutProjectUserDataRequestBody(BaseModel):
    data: PutProjectUserDataData


class PutProjectUserDataRequestTypedDict(TypedDict):
    project_id: str
    r"""Project ID or Slug"""
    user_data_id: str
    request_body: NotRequired[PutProjectUserDataRequestBodyTypedDict]


class PutProjectUserDataRequest(BaseModel):
    project_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""Project ID or Slug"""

    user_data_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    request_body: Annotated[
        Optional[PutProjectUserDataRequestBody],
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ] = None
