"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from latitudesh_python_sdk.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class RegionCountryTypedDict(TypedDict):
    slug: NotRequired[str]
    name: NotRequired[str]


class RegionCountry(BaseModel):
    slug: Optional[str] = None

    name: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["slug", "name"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class RegionAttributesTypedDict(TypedDict):
    slug: NotRequired[str]
    name: NotRequired[str]
    country: NotRequired[RegionCountryTypedDict]


class RegionAttributes(BaseModel):
    slug: Optional[str] = None

    name: Optional[str] = None

    country: Optional[RegionCountry] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["slug", "name", "country"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class RegionDataTypedDict(TypedDict):
    id: NotRequired[str]
    attributes: NotRequired[RegionAttributesTypedDict]


class RegionData(BaseModel):
    id: Optional[str] = None

    attributes: Optional[RegionAttributes] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["id", "attributes"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class RegionTypedDict(TypedDict):
    data: NotRequired[RegionDataTypedDict]


class Region(BaseModel):
    data: Optional[RegionData] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["data"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
