"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .role_data import RoleData, RoleDataTypedDict
from latitudesh_python_sdk.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class RoleMetaTypedDict(TypedDict):
    pass


class RoleMeta(BaseModel):
    pass


class RoleTypedDict(TypedDict):
    data: NotRequired[RoleDataTypedDict]
    meta: NotRequired[RoleMetaTypedDict]


class Role(BaseModel):
    data: Optional[RoleData] = None

    meta: Optional[RoleMeta] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["data", "meta"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
