"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from latitudesh_python_sdk.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class ServerActionType(str, Enum):
    ACTIONS = "actions"


class ServerActionAttributesTypedDict(TypedDict):
    status: NotRequired[str]


class ServerActionAttributes(BaseModel):
    status: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["status"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class ServerActionDataTypedDict(TypedDict):
    id: NotRequired[str]
    type: NotRequired[ServerActionType]
    attributes: NotRequired[ServerActionAttributesTypedDict]


class ServerActionData(BaseModel):
    id: Optional[str] = None

    type: Optional[ServerActionType] = None

    attributes: Optional[ServerActionAttributes] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["id", "type", "attributes"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class ServerActionMetaTypedDict(TypedDict):
    pass


class ServerActionMeta(BaseModel):
    pass


class ServerActionTypedDict(TypedDict):
    data: NotRequired[ServerActionDataTypedDict]
    meta: NotRequired[ServerActionMetaTypedDict]


class ServerAction(BaseModel):
    data: Optional[ServerActionData] = None

    meta: Optional[ServerActionMeta] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["data", "meta"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
