"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import date, datetime
from latitudesh_python_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
import pydantic
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class StorageUsageAttributesTypedDict(TypedDict):
    date_: NotRequired[date]
    r"""The day this usage row refers to"""
    storage_id: NotRequired[str]
    r"""The storage/bucket ID. A numeric value serialized as a string, e.g. \"42\"."""
    project_id: NotRequired[str]
    r"""The project ID. A numeric value serialized as a string, e.g. \"1234\"."""
    storage_type: NotRequired[Nullable[str]]
    r"""Storage kind. One of: object, file, block."""
    tier: NotRequired[Nullable[str]]
    r"""Performance tier. One of: high, standard."""
    region: NotRequired[str]
    bytes_: NotRequired[int]
    r"""Canonical storage usage for the day, in bytes"""
    raw_value: NotRequired[float]
    r"""The provider-reported usage value, in raw_unit"""
    raw_unit: NotRequired[str]
    r"""The unit raw_value is expressed in"""
    ingested_at: NotRequired[datetime]


class StorageUsageAttributes(BaseModel):
    date_: Annotated[Optional[date], pydantic.Field(alias="date")] = None
    r"""The day this usage row refers to"""

    storage_id: Optional[str] = None
    r"""The storage/bucket ID. A numeric value serialized as a string, e.g. \"42\"."""

    project_id: Optional[str] = None
    r"""The project ID. A numeric value serialized as a string, e.g. \"1234\"."""

    storage_type: OptionalNullable[str] = UNSET
    r"""Storage kind. One of: object, file, block."""

    tier: OptionalNullable[str] = UNSET
    r"""Performance tier. One of: high, standard."""

    region: Optional[str] = None

    bytes_: Annotated[Optional[int], pydantic.Field(alias="bytes")] = None
    r"""Canonical storage usage for the day, in bytes"""

    raw_value: Optional[float] = None
    r"""The provider-reported usage value, in raw_unit"""

    raw_unit: Optional[str] = None
    r"""The unit raw_value is expressed in"""

    ingested_at: Optional[datetime] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "date",
                "storage_id",
                "project_id",
                "storage_type",
                "tier",
                "region",
                "bytes",
                "raw_value",
                "raw_unit",
                "ingested_at",
            ]
        )
        nullable_fields = set(["storage_type", "tier"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class StorageUsageDataTypedDict(TypedDict):
    id: NotRequired[str]
    type: NotRequired[str]
    attributes: NotRequired[StorageUsageAttributesTypedDict]


class StorageUsageData(BaseModel):
    id: Optional[str] = None

    type: Optional[str] = None

    attributes: Optional[StorageUsageAttributes] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["id", "type", "attributes"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class StorageUsageTypedDict(TypedDict):
    data: NotRequired[List[StorageUsageDataTypedDict]]


class StorageUsage(BaseModel):
    data: Optional[List[StorageUsageData]] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["data"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


try:
    StorageUsageAttributes.model_rebuild()
except NameError:
    pass
