"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from latitudesh_python_sdk.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class StoragePlanDataType(str, Enum):
    STORAGE_PLANS = "storage_plans"


class StoragePlanDataPricingTypedDict(TypedDict):
    month: NotRequired[float]


class StoragePlanDataPricing(BaseModel):
    month: Optional[float] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["month"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class StoragePlanDataAttributesTypedDict(TypedDict):
    name: NotRequired[str]
    locations: NotRequired[List[str]]
    pricing: NotRequired[StoragePlanDataPricingTypedDict]


class StoragePlanDataAttributes(BaseModel):
    name: Optional[str] = None

    locations: Optional[List[str]] = None

    pricing: Optional[StoragePlanDataPricing] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["name", "locations", "pricing"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class StoragePlanDataTypedDict(TypedDict):
    id: NotRequired[str]
    type: NotRequired[StoragePlanDataType]
    attributes: NotRequired[StoragePlanDataAttributesTypedDict]


class StoragePlanData(BaseModel):
    id: Optional[str] = None

    type: Optional[StoragePlanDataType] = None

    attributes: Optional[StoragePlanDataAttributes] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["id", "type", "attributes"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
