"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from datetime import datetime
from latitudesh_python_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class TeamMembersRoleTypedDict(TypedDict):
    id: NotRequired[str]
    name: NotRequired[str]
    created_at: NotRequired[str]
    updated_at: NotRequired[str]


class TeamMembersRole(BaseModel):
    id: Optional[str] = None

    name: Optional[str] = None

    created_at: Optional[str] = None

    updated_at: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["id", "name", "created_at", "updated_at"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class TeamMembersAttributesTypedDict(TypedDict):
    first_name: NotRequired[str]
    last_name: NotRequired[str]
    email: NotRequired[str]
    mfa_enabled: NotRequired[bool]
    created_at: NotRequired[datetime]
    updated_at: NotRequired[datetime]
    last_login_at: NotRequired[Nullable[datetime]]
    role: NotRequired[TeamMembersRoleTypedDict]


class TeamMembersAttributes(BaseModel):
    first_name: Optional[str] = None

    last_name: Optional[str] = None

    email: Optional[str] = None

    mfa_enabled: Optional[bool] = None

    created_at: Optional[datetime] = None

    updated_at: Optional[datetime] = None

    last_login_at: OptionalNullable[datetime] = UNSET

    role: Optional[TeamMembersRole] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "first_name",
                "last_name",
                "email",
                "mfa_enabled",
                "created_at",
                "updated_at",
                "last_login_at",
                "role",
            ]
        )
        nullable_fields = set(["last_login_at"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class TeamMembersDataTypedDict(TypedDict):
    id: NotRequired[str]
    type: NotRequired[str]
    attributes: NotRequired[TeamMembersAttributesTypedDict]


class TeamMembersData(BaseModel):
    id: Optional[str] = None

    type: Optional[str] = None

    attributes: Optional[TeamMembersAttributes] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["id", "type", "attributes"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class TeamMembersTypedDict(TypedDict):
    data: NotRequired[List[TeamMembersDataTypedDict]]


class TeamMembers(BaseModel):
    data: Optional[List[TeamMembersData]] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["data"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
