"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .team import Team, TeamTypedDict
from latitudesh_python_sdk.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class TeamsMetaTypedDict(TypedDict):
    pass


class TeamsMeta(BaseModel):
    pass


class TeamsTypedDict(TypedDict):
    data: NotRequired[List[TeamTypedDict]]
    meta: NotRequired[TeamsMetaTypedDict]


class Teams(BaseModel):
    data: Optional[List[Team]] = None

    meta: Optional[TeamsMeta] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["data", "meta"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
