"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .virtual_machine_update_payload import (
    VirtualMachineUpdatePayload,
    VirtualMachineUpdatePayloadTypedDict,
)
from latitudesh_python_sdk.types import BaseModel
from latitudesh_python_sdk.utils import (
    FieldMetadata,
    PathParamMetadata,
    RequestMetadata,
)
from typing_extensions import Annotated, TypedDict


class UpdateVirtualMachineRequestTypedDict(TypedDict):
    virtual_machine_id: str
    virtual_machine_update_payload: VirtualMachineUpdatePayloadTypedDict


class UpdateVirtualMachineRequest(BaseModel):
    virtual_machine_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    virtual_machine_update_payload: Annotated[
        VirtualMachineUpdatePayload,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
