"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from latitudesh_python_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from latitudesh_python_sdk.utils import (
    FieldMetadata,
    PathParamMetadata,
    RequestMetadata,
)
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class UpdateServerServersType(str, Enum):
    SERVERS = "servers"


class UpdateServerServersBilling(str, Enum):
    r"""The server billing type. Accepts `hourly` and `monthly` for on demand projects and `yearly` for reserved projects."""

    HOURLY = "hourly"
    MONTHLY = "monthly"
    YEARLY = "yearly"


class UpdateServerServersAttributesTypedDict(TypedDict):
    hostname: NotRequired[str]
    billing: NotRequired[Nullable[UpdateServerServersBilling]]
    r"""The server billing type. Accepts `hourly` and `monthly` for on demand projects and `yearly` for reserved projects."""
    tags: NotRequired[Nullable[List[str]]]
    r"""List of Tag IDs"""
    project: NotRequired[str]
    r"""Project ID or slug to move the server to"""


class UpdateServerServersAttributes(BaseModel):
    hostname: Optional[str] = "new-hostname"

    billing: OptionalNullable[UpdateServerServersBilling] = UNSET
    r"""The server billing type. Accepts `hourly` and `monthly` for on demand projects and `yearly` for reserved projects."""

    tags: OptionalNullable[List[str]] = UNSET
    r"""List of Tag IDs"""

    project: Optional[str] = None
    r"""Project ID or slug to move the server to"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["hostname", "billing", "tags", "project"])
        nullable_fields = set(["billing", "tags"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class UpdateServerServersDataTypedDict(TypedDict):
    id: NotRequired[str]
    type: NotRequired[UpdateServerServersType]
    attributes: NotRequired[UpdateServerServersAttributesTypedDict]


class UpdateServerServersData(BaseModel):
    id: Optional[str] = "sv_81EVOtR1N4J2Z"

    type: Optional[UpdateServerServersType] = None

    attributes: Optional[UpdateServerServersAttributes] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["id", "type", "attributes"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class UpdateServerServersRequestBodyTypedDict(TypedDict):
    data: NotRequired[UpdateServerServersDataTypedDict]


class UpdateServerServersRequestBody(BaseModel):
    data: Optional[UpdateServerServersData] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["data"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class UpdateServerRequestTypedDict(TypedDict):
    server_id: str
    request_body: UpdateServerServersRequestBodyTypedDict


class UpdateServerRequest(BaseModel):
    server_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    request_body: Annotated[
        UpdateServerServersRequestBody,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
