"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from latitudesh_python_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from pydantic import model_serializer
from typing_extensions import NotRequired, TypedDict


class UpdateKubernetesClusterType(str, Enum):
    KUBERNETES_CLUSTERS = "kubernetes_clusters"


class UpdateKubernetesClusterAttributesTypedDict(TypedDict):
    worker_count: int
    r"""Desired number of worker nodes. Must be between 0 and 10."""
    worker_plan: NotRequired[Nullable[str]]
    r"""Plan slug for worker nodes. Required when scaling from 0 workers. Ignored when scaling an existing deployment."""


class UpdateKubernetesClusterAttributes(BaseModel):
    worker_count: int
    r"""Desired number of worker nodes. Must be between 0 and 10."""

    worker_plan: OptionalNullable[str] = UNSET
    r"""Plan slug for worker nodes. Required when scaling from 0 workers. Ignored when scaling an existing deployment."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["worker_plan"])
        nullable_fields = set(["worker_plan"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class UpdateKubernetesClusterDataTypedDict(TypedDict):
    type: UpdateKubernetesClusterType
    attributes: UpdateKubernetesClusterAttributesTypedDict


class UpdateKubernetesClusterData(BaseModel):
    type: UpdateKubernetesClusterType

    attributes: UpdateKubernetesClusterAttributes


class UpdateKubernetesClusterTypedDict(TypedDict):
    data: UpdateKubernetesClusterDataTypedDict


class UpdateKubernetesCluster(BaseModel):
    data: UpdateKubernetesClusterData
