"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .update_elastic_ip import UpdateElasticIP, UpdateElasticIPTypedDict
from latitudesh_python_sdk.types import BaseModel
from latitudesh_python_sdk.utils import (
    FieldMetadata,
    PathParamMetadata,
    RequestMetadata,
)
from typing_extensions import Annotated, TypedDict


class UpdateElasticIPRequestTypedDict(TypedDict):
    elastic_ip_id: str
    r"""The Elastic IP ID"""
    update_elastic_ip: UpdateElasticIPTypedDict


class UpdateElasticIPRequest(BaseModel):
    elastic_ip_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""The Elastic IP ID"""

    update_elastic_ip: Annotated[
        UpdateElasticIP,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
