"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .filesystem_data import FilesystemData, FilesystemDataTypedDict
from enum import Enum
from latitudesh_python_sdk.types import BaseModel, UNSET_SENTINEL
from latitudesh_python_sdk.utils import (
    FieldMetadata,
    PathParamMetadata,
    RequestMetadata,
)
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class UpdateFilesystemFilesystemStorageType(str, Enum):
    FILESYSTEMS = "filesystems"


class UpdateFilesystemFilesystemStorageAttributesTypedDict(TypedDict):
    size_in_gb: int
    r"""Size in GB (not required, default is 1500)"""


class UpdateFilesystemFilesystemStorageAttributes(BaseModel):
    size_in_gb: int
    r"""Size in GB (not required, default is 1500)"""


class UpdateFilesystemFilesystemStorageDataTypedDict(TypedDict):
    type: UpdateFilesystemFilesystemStorageType
    attributes: UpdateFilesystemFilesystemStorageAttributesTypedDict
    id: NotRequired[str]
    r"""Filesystem ID"""


class UpdateFilesystemFilesystemStorageData(BaseModel):
    type: UpdateFilesystemFilesystemStorageType

    attributes: UpdateFilesystemFilesystemStorageAttributes

    id: Optional[str] = None
    r"""Filesystem ID"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["id"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class UpdateFilesystemFilesystemStorageRequestBodyTypedDict(TypedDict):
    data: UpdateFilesystemFilesystemStorageDataTypedDict


class UpdateFilesystemFilesystemStorageRequestBody(BaseModel):
    data: UpdateFilesystemFilesystemStorageData


class UpdateFilesystemRequestTypedDict(TypedDict):
    filesystem_id: str
    request_body: UpdateFilesystemFilesystemStorageRequestBodyTypedDict


class UpdateFilesystemRequest(BaseModel):
    filesystem_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    request_body: Annotated[
        UpdateFilesystemFilesystemStorageRequestBody,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]


class UpdateFilesystemResponseBodyTypedDict(TypedDict):
    r"""Success"""

    data: NotRequired[FilesystemDataTypedDict]


class UpdateFilesystemResponseBody(BaseModel):
    r"""Success"""

    data: Optional[FilesystemData] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["data"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
