"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from latitudesh_python_sdk.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class UpdateLksClusterType(str, Enum):
    LKS_CLUSTERS = "lks_clusters"


class UpdateLksClusterAttributesTypedDict(TypedDict):
    r"""At least one of name, description or kubernetes_version must be provided."""

    name: NotRequired[str]
    description: NotRequired[str]
    kubernetes_version: NotRequired[str]
    r"""Setting a newer patch consents to a control-plane upgrade. Must not be lower than the current patch (422 DOWNGRADE_NOT_ALLOWED)"""


class UpdateLksClusterAttributes(BaseModel):
    r"""At least one of name, description or kubernetes_version must be provided."""

    name: Optional[str] = None

    description: Optional[str] = None

    kubernetes_version: Optional[str] = None
    r"""Setting a newer patch consents to a control-plane upgrade. Must not be lower than the current patch (422 DOWNGRADE_NOT_ALLOWED)"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["name", "description", "kubernetes_version"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class UpdateLksClusterDataTypedDict(TypedDict):
    type: UpdateLksClusterType
    attributes: NotRequired[UpdateLksClusterAttributesTypedDict]
    r"""At least one of name, description or kubernetes_version must be provided."""


class UpdateLksClusterData(BaseModel):
    type: UpdateLksClusterType

    attributes: Optional[UpdateLksClusterAttributes] = None
    r"""At least one of name, description or kubernetes_version must be provided."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["attributes"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class UpdateLksClusterTypedDict(TypedDict):
    data: UpdateLksClusterDataTypedDict


class UpdateLksCluster(BaseModel):
    data: UpdateLksClusterData
