"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from latitudesh_python_sdk.types import BaseModel, UNSET_SENTINEL
from latitudesh_python_sdk.utils import (
    FieldMetadata,
    PathParamMetadata,
    RequestMetadata,
)
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class UpdateVirtualNetworkPrivateNetworksType(str, Enum):
    VIRTUAL_NETWORKS = "virtual_networks"


class UpdateVirtualNetworkPrivateNetworksAttributesTypedDict(TypedDict):
    tags: NotRequired[List[str]]
    description: NotRequired[str]


class UpdateVirtualNetworkPrivateNetworksAttributes(BaseModel):
    tags: Optional[List[str]] = None

    description: Optional[str] = "Test virtual network update"

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["tags", "description"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class UpdateVirtualNetworkPrivateNetworksDataTypedDict(TypedDict):
    id: str
    type: UpdateVirtualNetworkPrivateNetworksType
    attributes: NotRequired[UpdateVirtualNetworkPrivateNetworksAttributesTypedDict]


class UpdateVirtualNetworkPrivateNetworksData(BaseModel):
    id: str

    type: UpdateVirtualNetworkPrivateNetworksType

    attributes: Optional[UpdateVirtualNetworkPrivateNetworksAttributes] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["attributes"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class UpdateVirtualNetworkPrivateNetworksRequestBodyTypedDict(TypedDict):
    data: UpdateVirtualNetworkPrivateNetworksDataTypedDict


class UpdateVirtualNetworkPrivateNetworksRequestBody(BaseModel):
    data: UpdateVirtualNetworkPrivateNetworksData


class UpdateVirtualNetworkRequestTypedDict(TypedDict):
    vlan_id: str
    r"""The Virtual Network ID"""
    request_body: UpdateVirtualNetworkPrivateNetworksRequestBodyTypedDict


class UpdateVirtualNetworkRequest(BaseModel):
    vlan_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]
    r"""The Virtual Network ID"""

    request_body: Annotated[
        UpdateVirtualNetworkPrivateNetworksRequestBody,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]
