"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .api_key import APIKey, APIKeyTypedDict
from .update_api_key import UpdateAPIKey, UpdateAPIKeyTypedDict
from latitudesh_python_sdk.types import BaseModel, UNSET_SENTINEL
from latitudesh_python_sdk.utils import (
    FieldMetadata,
    PathParamMetadata,
    RequestMetadata,
)
from pydantic import model_serializer
from typing import Optional
from typing_extensions import Annotated, NotRequired, TypedDict


class UpdateAPIKeyRequestTypedDict(TypedDict):
    api_key_id: str
    update_api_key: UpdateAPIKeyTypedDict


class UpdateAPIKeyRequest(BaseModel):
    api_key_id: Annotated[
        str, FieldMetadata(path=PathParamMetadata(style="simple", explode=False))
    ]

    update_api_key: Annotated[
        UpdateAPIKey,
        FieldMetadata(request=RequestMetadata(media_type="application/json")),
    ]


class UpdateAPIKeyResponseBodyTypedDict(TypedDict):
    r"""Success - Update name without rotating token"""

    data: NotRequired[APIKeyTypedDict]


class UpdateAPIKeyResponseBody(BaseModel):
    r"""Success - Update name without rotating token"""

    data: Optional[APIKey] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["data"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
