"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from latitudesh_python_sdk.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class UserUpdateAttributesTypedDict(TypedDict):
    first_name: NotRequired[str]
    last_name: NotRequired[str]
    email: NotRequired[str]
    authentication_factor_id: NotRequired[str]
    role: NotRequired[str]


class UserUpdateAttributes(BaseModel):
    first_name: Optional[str] = None

    last_name: Optional[str] = None

    email: Optional[str] = None

    authentication_factor_id: Optional[str] = None

    role: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["first_name", "last_name", "email", "authentication_factor_id", "role"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class UserUpdateTypedDict(TypedDict):
    id: NotRequired[str]
    attributes: NotRequired[UserUpdateAttributesTypedDict]


class UserUpdate(BaseModel):
    id: Optional[str] = None

    attributes: Optional[UserUpdateAttributes] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["id", "attributes"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
