"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .user_data_object import UserDataObject, UserDataObjectTypedDict
from latitudesh_python_sdk.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class UserDataMetaTypedDict(TypedDict):
    pass


class UserDataMeta(BaseModel):
    pass


class UserDataTypedDict(TypedDict):
    data: NotRequired[List[UserDataObjectTypedDict]]
    meta: NotRequired[UserDataMetaTypedDict]


class UserData(BaseModel):
    data: Optional[List[UserDataObject]] = None

    meta: Optional[UserDataMeta] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["data", "meta"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
