"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from latitudesh_python_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class VirtualMachinePayloadType(str, Enum):
    VIRTUAL_MACHINES = "virtual_machines"


class VirtualMachinePayloadAttributesTypedDict(TypedDict):
    name: NotRequired[str]
    plan: NotRequired[Nullable[str]]
    r"""The plan ID or Slug for the Virtual Machine"""
    ssh_keys: NotRequired[Nullable[List[str]]]
    project: NotRequired[str]
    operating_system: NotRequired[Nullable[str]]
    r"""The operating system slug for the Virtual Machine. If not specified, defaults to ubuntu-24-04 for CPU plans or ubuntu24_ml_in_a_box for GPU plans."""


class VirtualMachinePayloadAttributes(BaseModel):
    name: Optional[str] = "my-vm"

    plan: OptionalNullable[str] = UNSET
    r"""The plan ID or Slug for the Virtual Machine"""

    ssh_keys: OptionalNullable[List[str]] = UNSET

    project: Optional[str] = "my-project"

    operating_system: OptionalNullable[str] = UNSET
    r"""The operating system slug for the Virtual Machine. If not specified, defaults to ubuntu-24-04 for CPU plans or ubuntu24_ml_in_a_box for GPU plans."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["name", "plan", "ssh_keys", "project", "operating_system"]
        )
        nullable_fields = set(["plan", "ssh_keys", "operating_system"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class VirtualMachinePayloadDataTypedDict(TypedDict):
    type: NotRequired[VirtualMachinePayloadType]
    attributes: NotRequired[VirtualMachinePayloadAttributesTypedDict]


class VirtualMachinePayloadData(BaseModel):
    type: Optional[VirtualMachinePayloadType] = None

    attributes: Optional[VirtualMachinePayloadAttributes] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["type", "attributes"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class VirtualMachinePayloadTypedDict(TypedDict):
    data: NotRequired[VirtualMachinePayloadDataTypedDict]


class VirtualMachinePayload(BaseModel):
    data: Optional[VirtualMachinePayloadData] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["data"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
