"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from latitudesh_python_sdk.types import BaseModel
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class VirtualMachinePayloadType(str, Enum):
    VIRTUAL_MACHINES = "virtual_machines"


class VirtualMachinePayloadAttributesTypedDict(TypedDict):
    name: NotRequired[str]
    plan: NotRequired[str]
    site: NotRequired[str]
    r"""The site slug where the virtual machine will be deployed. Defaults to 'DAL' if not specified. To see which sites are available for a given plan, check the 'available' array in the plan's regions."""
    ssh_keys: NotRequired[List[str]]
    project: NotRequired[str]


class VirtualMachinePayloadAttributes(BaseModel):
    name: Optional[str] = "my-vm"

    plan: Optional[str] = None

    site: Optional[str] = None
    r"""The site slug where the virtual machine will be deployed. Defaults to 'DAL' if not specified. To see which sites are available for a given plan, check the 'available' array in the plan's regions."""

    ssh_keys: Optional[List[str]] = None

    project: Optional[str] = "my-project"


class VirtualMachinePayloadDataTypedDict(TypedDict):
    type: NotRequired[VirtualMachinePayloadType]
    attributes: NotRequired[VirtualMachinePayloadAttributesTypedDict]


class VirtualMachinePayloadData(BaseModel):
    type: Optional[VirtualMachinePayloadType] = None

    attributes: Optional[VirtualMachinePayloadAttributes] = None


class VirtualMachinePayloadTypedDict(TypedDict):
    data: NotRequired[VirtualMachinePayloadDataTypedDict]


class VirtualMachinePayload(BaseModel):
    data: Optional[VirtualMachinePayloadData] = None
