"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .project_include import ProjectInclude, ProjectIncludeTypedDict
from .team_include import TeamInclude, TeamIncludeTypedDict
from enum import Enum
from latitudesh_python_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class VirtualMachineAttributesType(str, Enum):
    VIRTUAL_MACHINES = "virtual_machines"


class VirtualMachineAttributesStatus(str, Enum):
    RUNNING = "Running"
    CONFIGURING_NETWORK = "Configuring network"
    STARTING = "Starting"
    SCHEDULING = "Scheduling"
    SCHEDULED = "Scheduled"
    DESTROYING = "Destroying"


class VirtualMachineAttributesFeaturesTypedDict(TypedDict):
    r"""Features supported by this operating system"""

    raid: NotRequired[bool]
    r"""Whether RAID is supported"""
    ssh_keys: NotRequired[bool]
    r"""Whether SSH keys are supported"""
    user_data: NotRequired[bool]
    r"""Whether user data is supported"""


class VirtualMachineAttributesFeatures(BaseModel):
    r"""Features supported by this operating system"""

    raid: Optional[bool] = None
    r"""Whether RAID is supported"""

    ssh_keys: Optional[bool] = None
    r"""Whether SSH keys are supported"""

    user_data: Optional[bool] = None
    r"""Whether user data is supported"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["raid", "ssh_keys", "user_data"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class VirtualMachineAttributesDistroTypedDict(TypedDict):
    r"""Distribution information"""

    name: NotRequired[str]
    r"""The name of the Linux distribution"""
    slug: NotRequired[str]
    r"""The slug of the Linux distribution"""
    series: NotRequired[str]
    r"""The distribution series code name"""


class VirtualMachineAttributesDistro(BaseModel):
    r"""Distribution information"""

    name: Optional[str] = None
    r"""The name of the Linux distribution"""

    slug: Optional[str] = None
    r"""The slug of the Linux distribution"""

    series: Optional[str] = None
    r"""The distribution series code name"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["name", "slug", "series"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class VirtualMachineAttributesOperatingSystemTypedDict(TypedDict):
    r"""The operating system installed on the virtual machine"""

    name: NotRequired[str]
    r"""The full name of the operating system"""
    slug: NotRequired[str]
    r"""The unique slug identifier for the operating system"""
    version: NotRequired[str]
    r"""The version of the operating system"""
    features: NotRequired[VirtualMachineAttributesFeaturesTypedDict]
    r"""Features supported by this operating system"""
    distro: NotRequired[VirtualMachineAttributesDistroTypedDict]
    r"""Distribution information"""


class VirtualMachineAttributesOperatingSystem(BaseModel):
    r"""The operating system installed on the virtual machine"""

    name: Optional[str] = None
    r"""The full name of the operating system"""

    slug: Optional[str] = None
    r"""The unique slug identifier for the operating system"""

    version: Optional[str] = None
    r"""The version of the operating system"""

    features: Optional[VirtualMachineAttributesFeatures] = None
    r"""Features supported by this operating system"""

    distro: Optional[VirtualMachineAttributesDistro] = None
    r"""Distribution information"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["name", "slug", "version", "features", "distro"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class CredentialsTypedDict(TypedDict):
    r"""SSH credentials for connecting to the virtual machine. Only available when the VM is running."""

    username: NotRequired[str]
    r"""The SSH username for the VM, determined by the operating system (e.g., ubuntu, centos, ec2-user). Defaults to ubuntu if not specified by the OS."""
    host: NotRequired[str]
    password: NotRequired[str]
    ssh_keys: NotRequired[List[str]]


class Credentials(BaseModel):
    r"""SSH credentials for connecting to the virtual machine. Only available when the VM is running."""

    username: Optional[str] = None
    r"""The SSH username for the VM, determined by the operating system (e.g., ubuntu, centos, ec2-user). Defaults to ubuntu if not specified by the OS."""

    host: Optional[str] = None

    password: Optional[str] = None

    ssh_keys: Optional[List[str]] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["username", "host", "password", "ssh_keys"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class VirtualMachineAttributesPlanTypedDict(TypedDict):
    id: NotRequired[str]
    name: NotRequired[str]


class VirtualMachineAttributesPlan(BaseModel):
    id: Optional[str] = None

    name: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["id", "name"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class VirtualMachineAttributesSpecsTypedDict(TypedDict):
    vcpu: NotRequired[Nullable[int]]
    ram: NotRequired[Nullable[str]]
    storage: NotRequired[Nullable[str]]
    nic: NotRequired[Nullable[str]]
    gpu: NotRequired[Nullable[str]]


class VirtualMachineAttributesSpecs(BaseModel):
    vcpu: OptionalNullable[int] = UNSET

    ram: OptionalNullable[str] = UNSET

    storage: OptionalNullable[str] = UNSET

    nic: OptionalNullable[str] = UNSET

    gpu: OptionalNullable[str] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["vcpu", "ram", "storage", "nic", "gpu"])
        nullable_fields = set(["vcpu", "ram", "storage", "nic", "gpu"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class VirtualMachineAttributesTagsTypedDict(TypedDict):
    id: NotRequired[str]
    name: NotRequired[str]
    description: NotRequired[Nullable[str]]
    color: NotRequired[Nullable[str]]


class VirtualMachineAttributesTags(BaseModel):
    id: Optional[str] = None

    name: Optional[str] = None

    description: OptionalNullable[str] = UNSET

    color: OptionalNullable[str] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["id", "name", "description", "color"])
        nullable_fields = set(["description", "color"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class VirtualMachineAttributesAttributesTypedDict(TypedDict):
    name: NotRequired[str]
    created_at: NotRequired[str]
    status: NotRequired[VirtualMachineAttributesStatus]
    primary_ipv4: NotRequired[Nullable[str]]
    operating_system: NotRequired[
        Nullable[VirtualMachineAttributesOperatingSystemTypedDict]
    ]
    r"""The operating system installed on the virtual machine"""
    credentials: NotRequired[Nullable[CredentialsTypedDict]]
    r"""SSH credentials for connecting to the virtual machine. Only available when the VM is running."""
    site: NotRequired[Nullable[str]]
    billing: NotRequired[Nullable[str]]
    user_data: NotRequired[Nullable[str]]
    r"""Encoded ID of the user data record applied to this VM, if any"""
    plan: NotRequired[VirtualMachineAttributesPlanTypedDict]
    specs: NotRequired[VirtualMachineAttributesSpecsTypedDict]
    tags: NotRequired[List[VirtualMachineAttributesTagsTypedDict]]
    team: NotRequired[TeamIncludeTypedDict]
    project: NotRequired[ProjectIncludeTypedDict]
    pending_restart: NotRequired[bool]
    r"""Opt-in extra field. Request via `extra_fields[virtual_machines]=pending_restart`."""


class VirtualMachineAttributesAttributes(BaseModel):
    name: Optional[str] = None

    created_at: Optional[str] = None

    status: Optional[VirtualMachineAttributesStatus] = None

    primary_ipv4: OptionalNullable[str] = UNSET

    operating_system: OptionalNullable[VirtualMachineAttributesOperatingSystem] = UNSET
    r"""The operating system installed on the virtual machine"""

    credentials: OptionalNullable[Credentials] = UNSET
    r"""SSH credentials for connecting to the virtual machine. Only available when the VM is running."""

    site: OptionalNullable[str] = UNSET

    billing: OptionalNullable[str] = UNSET

    user_data: OptionalNullable[str] = UNSET
    r"""Encoded ID of the user data record applied to this VM, if any"""

    plan: Optional[VirtualMachineAttributesPlan] = None

    specs: Optional[VirtualMachineAttributesSpecs] = None

    tags: Optional[List[VirtualMachineAttributesTags]] = None

    team: Optional[TeamInclude] = None

    project: Optional[ProjectInclude] = None

    pending_restart: Optional[bool] = None
    r"""Opt-in extra field. Request via `extra_fields[virtual_machines]=pending_restart`."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "name",
                "created_at",
                "status",
                "primary_ipv4",
                "operating_system",
                "credentials",
                "site",
                "billing",
                "user_data",
                "plan",
                "specs",
                "tags",
                "team",
                "project",
                "pending_restart",
            ]
        )
        nullable_fields = set(
            [
                "primary_ipv4",
                "operating_system",
                "credentials",
                "site",
                "billing",
                "user_data",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class VirtualMachineAttributesTypedDict(TypedDict):
    id: NotRequired[str]
    type: NotRequired[VirtualMachineAttributesType]
    attributes: NotRequired[VirtualMachineAttributesAttributesTypedDict]


class VirtualMachineAttributes(BaseModel):
    id: Optional[str] = None

    type: Optional[VirtualMachineAttributesType] = None

    attributes: Optional[VirtualMachineAttributesAttributes] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["id", "type", "attributes"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
