"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .virtual_machine_network_attachment_resource import (
    VirtualMachineNetworkAttachmentResource,
    VirtualMachineNetworkAttachmentResourceTypedDict,
)
from latitudesh_python_sdk.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class VirtualMachineNetworkAttachmentsTypedDict(TypedDict):
    data: NotRequired[List[VirtualMachineNetworkAttachmentResourceTypedDict]]


class VirtualMachineNetworkAttachments(BaseModel):
    data: Optional[List[VirtualMachineNetworkAttachmentResource]] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["data"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
