"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .project_include import ProjectInclude, ProjectIncludeTypedDict
from .team_include import TeamInclude, TeamIncludeTypedDict
from enum import Enum
from latitudesh_python_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class VirtualMachineRestoreAttributesType(str, Enum):
    VIRTUAL_MACHINE_RESTORES = "virtual_machine_restores"


class VirtualMachineRestoreAttributesStatus(str, Enum):
    CREATING = "Creating"
    READY = "Ready"
    FAILED = "Failed"


class BackupTypedDict(TypedDict):
    id: NotRequired[str]


class Backup(BaseModel):
    id: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["id"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class VirtualMachineRestoreAttributesVirtualMachineTypedDict(TypedDict):
    r"""The restored VM. Null until the restore is ready."""

    id: NotRequired[str]
    name: NotRequired[str]


class VirtualMachineRestoreAttributesVirtualMachine(BaseModel):
    r"""The restored VM. Null until the restore is ready."""

    id: Optional[str] = None

    name: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["id", "name"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class VirtualMachineRestoreAttributesAttributesTypedDict(TypedDict):
    status: NotRequired[VirtualMachineRestoreAttributesStatus]
    created_at: NotRequired[str]
    backup: NotRequired[BackupTypedDict]
    virtual_machine: NotRequired[
        Nullable[VirtualMachineRestoreAttributesVirtualMachineTypedDict]
    ]
    r"""The restored VM. Null until the restore is ready."""
    team: NotRequired[TeamIncludeTypedDict]
    project: NotRequired[ProjectIncludeTypedDict]


class VirtualMachineRestoreAttributesAttributes(BaseModel):
    status: Optional[VirtualMachineRestoreAttributesStatus] = None

    created_at: Optional[str] = None

    backup: Optional[Backup] = None

    virtual_machine: OptionalNullable[VirtualMachineRestoreAttributesVirtualMachine] = (
        UNSET
    )
    r"""The restored VM. Null until the restore is ready."""

    team: Optional[TeamInclude] = None

    project: Optional[ProjectInclude] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["status", "created_at", "backup", "virtual_machine", "team", "project"]
        )
        nullable_fields = set(["virtual_machine"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class VirtualMachineRestoreAttributesTypedDict(TypedDict):
    id: NotRequired[str]
    type: NotRequired[VirtualMachineRestoreAttributesType]
    attributes: NotRequired[VirtualMachineRestoreAttributesAttributesTypedDict]


class VirtualMachineRestoreAttributes(BaseModel):
    id: Optional[str] = None

    type: Optional[VirtualMachineRestoreAttributesType] = None

    attributes: Optional[VirtualMachineRestoreAttributesAttributes] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["id", "type", "attributes"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
