"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from latitudesh_python_sdk.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class VirtualNetworkAssignmentDataType(str, Enum):
    VIRTUAL_NETWORK_ASSIGNMENT = "virtual_network_assignment"


class VirtualNetworkAssignmentDataServerTypedDict(TypedDict):
    id: NotRequired[str]
    hostname: NotRequired[str]
    label: NotRequired[str]
    locked: NotRequired[bool]
    status: NotRequired[str]


class VirtualNetworkAssignmentDataServer(BaseModel):
    id: Optional[str] = None

    hostname: Optional[str] = None

    label: Optional[str] = None

    locked: Optional[bool] = None

    status: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["id", "hostname", "label", "locked", "status"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class VirtualNetworkAssignmentDataAttributesTypedDict(TypedDict):
    virtual_network_id: NotRequired[str]
    vid: NotRequired[int]
    description: NotRequired[str]
    status: NotRequired[str]
    server: NotRequired[VirtualNetworkAssignmentDataServerTypedDict]


class VirtualNetworkAssignmentDataAttributes(BaseModel):
    virtual_network_id: Optional[str] = None

    vid: Optional[int] = None

    description: Optional[str] = None

    status: Optional[str] = None

    server: Optional[VirtualNetworkAssignmentDataServer] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            ["virtual_network_id", "vid", "description", "status", "server"]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class VirtualNetworkAssignmentDataTypedDict(TypedDict):
    id: NotRequired[str]
    type: NotRequired[VirtualNetworkAssignmentDataType]
    attributes: NotRequired[VirtualNetworkAssignmentDataAttributesTypedDict]


class VirtualNetworkAssignmentData(BaseModel):
    id: Optional[str] = None

    type: Optional[VirtualNetworkAssignmentDataType] = None

    attributes: Optional[VirtualNetworkAssignmentDataAttributes] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["id", "type", "attributes"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
