"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from enum import Enum
from latitudesh_python_sdk.types import BaseModel, UNSET_SENTINEL
from pydantic import model_serializer
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class VirtualMachineNetworkAttachmentResourceType(str, Enum):
    VIRTUAL_MACHINE_NETWORK_ATTACHMENTS = "virtual_machine_network_attachments"


class VirtualMachineNetworkAttachmentResourceAttributesTypedDict(TypedDict):
    virtual_network_id: NotRequired[str]
    r"""The encoded VLAN id_hash"""
    vid: NotRequired[int]
    r"""The 802.1Q VLAN ID"""
    pending_restart: NotRequired[bool]
    r"""True if the attachment requires a VM restart to take effect"""


class VirtualMachineNetworkAttachmentResourceAttributes(BaseModel):
    virtual_network_id: Optional[str] = None
    r"""The encoded VLAN id_hash"""

    vid: Optional[int] = None
    r"""The 802.1Q VLAN ID"""

    pending_restart: Optional[bool] = None
    r"""True if the attachment requires a VM restart to take effect"""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["virtual_network_id", "vid", "pending_restart"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class VirtualMachineNetworkAttachmentResourceTypedDict(TypedDict):
    id: NotRequired[str]
    r"""The VLAN id_hash of the attachment"""
    type: NotRequired[VirtualMachineNetworkAttachmentResourceType]
    attributes: NotRequired[VirtualMachineNetworkAttachmentResourceAttributesTypedDict]


class VirtualMachineNetworkAttachmentResource(BaseModel):
    id: Optional[str] = None
    r"""The VLAN id_hash of the attachment"""

    type: Optional[VirtualMachineNetworkAttachmentResourceType] = None

    attributes: Optional[VirtualMachineNetworkAttachmentResourceAttributes] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["id", "type", "attributes"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
