"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .project_include import ProjectInclude, ProjectIncludeTypedDict
from .team_include import TeamInclude, TeamIncludeTypedDict
from datetime import datetime
from enum import Enum
from latitudesh_python_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class VolumeDataType(str, Enum):
    VOLUMES = "volumes"


class InitiatorsTypedDict(TypedDict):
    nqn: NotRequired[str]


class Initiators(BaseModel):
    nqn: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["nqn"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class VolumeDataAttributesTypedDict(TypedDict):
    name: NotRequired[str]
    size_in_gb: NotRequired[int]
    created_at: NotRequired[datetime]
    namespace_id: NotRequired[Nullable[str]]
    connector_id: NotRequired[str]
    initiators: NotRequired[List[InitiatorsTypedDict]]
    project: NotRequired[ProjectIncludeTypedDict]
    team: NotRequired[TeamIncludeTypedDict]


class VolumeDataAttributes(BaseModel):
    name: Optional[str] = None

    size_in_gb: Optional[int] = None

    created_at: Optional[datetime] = None

    namespace_id: OptionalNullable[str] = UNSET

    connector_id: Optional[str] = None

    initiators: Optional[List[Initiators]] = None

    project: Optional[ProjectInclude] = None

    team: Optional[TeamInclude] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "name",
                "size_in_gb",
                "created_at",
                "namespace_id",
                "connector_id",
                "initiators",
                "project",
                "team",
            ]
        )
        nullable_fields = set(["namespace_id"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class VolumeDataTypedDict(TypedDict):
    id: NotRequired[str]
    type: NotRequired[VolumeDataType]
    attributes: NotRequired[VolumeDataAttributesTypedDict]


class VolumeData(BaseModel):
    id: Optional[str] = None

    type: Optional[VolumeDataType] = None

    attributes: Optional[VolumeDataAttributes] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["id", "type", "attributes"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k)

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
