"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from .project_include import ProjectInclude, ProjectIncludeTypedDict
from .team_include import TeamInclude, TeamIncludeTypedDict
from datetime import datetime
from enum import Enum
from latitudesh_python_sdk.types import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UNSET,
    UNSET_SENTINEL,
)
from pydantic import model_serializer
from typing import List, Optional
from typing_extensions import NotRequired, TypedDict


class VolumeDataType(str, Enum):
    VOLUMES = "volumes"


class InitiatorsTypedDict(TypedDict):
    nqn: NotRequired[str]


class Initiators(BaseModel):
    nqn: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["nqn"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class BlockTypedDict(TypedDict):
    r"""NVMe-TCP block mapping of a high performance volume. Null for volumes that are not mapped to a server."""

    status: NotRequired[Nullable[str]]
    r"""Mapping lifecycle state: \"mapping\" while the mapping is being applied, \"mapped\" once the server can access the volume, or \"failed\". Mapping is asynchronous, so poll the volume until this reaches a terminal state."""
    nqn: NotRequired[Nullable[str]]
    r"""NVMe Qualified Name of the mapped server."""
    nsid: NotRequired[Nullable[int]]
    r"""NVMe namespace ID of the mapping."""
    server_id: NotRequired[Nullable[str]]
    r"""ID of the server the volume is mapped to."""


class Block(BaseModel):
    r"""NVMe-TCP block mapping of a high performance volume. Null for volumes that are not mapped to a server."""

    status: OptionalNullable[str] = UNSET
    r"""Mapping lifecycle state: \"mapping\" while the mapping is being applied, \"mapped\" once the server can access the volume, or \"failed\". Mapping is asynchronous, so poll the volume until this reaches a terminal state."""

    nqn: OptionalNullable[str] = UNSET
    r"""NVMe Qualified Name of the mapped server."""

    nsid: OptionalNullable[int] = UNSET
    r"""NVMe namespace ID of the mapping."""

    server_id: OptionalNullable[str] = UNSET
    r"""ID of the server the volume is mapped to."""

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["status", "nqn", "nsid", "server_id"])
        nullable_fields = set(["status", "nqn", "nsid", "server_id"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class VolumeDataSiteTypedDict(TypedDict):
    id: NotRequired[str]
    name: NotRequired[str]
    slug: NotRequired[str]
    facility: NotRequired[str]


class VolumeDataSite(BaseModel):
    id: Optional[str] = None

    name: Optional[str] = None

    slug: Optional[str] = None

    facility: Optional[str] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["id", "name", "slug", "facility"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m


class VolumeDataRegionTypedDict(TypedDict):
    city: NotRequired[Nullable[str]]
    country: NotRequired[Nullable[str]]
    site: NotRequired[Nullable[VolumeDataSiteTypedDict]]


class VolumeDataRegion(BaseModel):
    city: OptionalNullable[str] = UNSET

    country: OptionalNullable[str] = UNSET

    site: OptionalNullable[VolumeDataSite] = UNSET

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["city", "country", "site"])
        nullable_fields = set(["city", "country", "site"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class VolumeDataAttributesTypedDict(TypedDict):
    name: NotRequired[str]
    size_in_gb: NotRequired[int]
    created_at: NotRequired[Nullable[datetime]]
    namespace_id: NotRequired[Nullable[str]]
    connector_id: NotRequired[Nullable[str]]
    initiators: NotRequired[Nullable[List[InitiatorsTypedDict]]]
    block: NotRequired[Nullable[BlockTypedDict]]
    r"""NVMe-TCP block mapping of a high performance volume. Null for volumes that are not mapped to a server."""
    keyring: NotRequired[Nullable[str]]
    r"""Keyring secret used to connect to the volume. Returned only for dashboard-origin requests; null until the volume is provisioned."""
    cluster_user: NotRequired[Nullable[str]]
    r"""Cluster user used to connect to the volume. Returned only for dashboard-origin requests; null until the volume is provisioned."""
    volume_path: NotRequired[Nullable[str]]
    r"""Path of the volume inside the cluster. Returned only for dashboard-origin requests; null until the volume is provisioned."""
    region: NotRequired[Nullable[VolumeDataRegionTypedDict]]
    project: NotRequired[ProjectIncludeTypedDict]
    team: NotRequired[TeamIncludeTypedDict]


class VolumeDataAttributes(BaseModel):
    name: Optional[str] = None

    size_in_gb: Optional[int] = None

    created_at: OptionalNullable[datetime] = UNSET

    namespace_id: OptionalNullable[str] = UNSET

    connector_id: OptionalNullable[str] = UNSET

    initiators: OptionalNullable[List[Initiators]] = UNSET

    block: OptionalNullable[Block] = UNSET
    r"""NVMe-TCP block mapping of a high performance volume. Null for volumes that are not mapped to a server."""

    keyring: OptionalNullable[str] = UNSET
    r"""Keyring secret used to connect to the volume. Returned only for dashboard-origin requests; null until the volume is provisioned."""

    cluster_user: OptionalNullable[str] = UNSET
    r"""Cluster user used to connect to the volume. Returned only for dashboard-origin requests; null until the volume is provisioned."""

    volume_path: OptionalNullable[str] = UNSET
    r"""Path of the volume inside the cluster. Returned only for dashboard-origin requests; null until the volume is provisioned."""

    region: OptionalNullable[VolumeDataRegion] = UNSET

    project: Optional[ProjectInclude] = None

    team: Optional[TeamInclude] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(
            [
                "name",
                "size_in_gb",
                "created_at",
                "namespace_id",
                "connector_id",
                "initiators",
                "block",
                "keyring",
                "cluster_user",
                "volume_path",
                "region",
                "project",
                "team",
            ]
        )
        nullable_fields = set(
            [
                "created_at",
                "namespace_id",
                "connector_id",
                "initiators",
                "block",
                "keyring",
                "cluster_user",
                "volume_path",
                "region",
            ]
        )
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))
            is_nullable_and_explicitly_set = (
                k in nullable_fields
                and (self.__pydantic_fields_set__.intersection({n}))  # pylint: disable=no-member
            )

            if val != UNSET_SENTINEL:
                if (
                    val is not None
                    or k not in optional_fields
                    or is_nullable_and_explicitly_set
                ):
                    m[k] = val

        return m


class VolumeDataTypedDict(TypedDict):
    id: NotRequired[str]
    type: NotRequired[VolumeDataType]
    attributes: NotRequired[VolumeDataAttributesTypedDict]


class VolumeData(BaseModel):
    id: Optional[str] = None

    type: Optional[VolumeDataType] = None

    attributes: Optional[VolumeDataAttributes] = None

    @model_serializer(mode="wrap")
    def serialize_model(self, handler):
        optional_fields = set(["id", "type", "attributes"])
        serialized = handler(self)
        m = {}

        for n, f in type(self).model_fields.items():
            k = f.alias or n
            val = serialized.get(k, serialized.get(n))

            if val != UNSET_SENTINEL:
                if val is not None or k not in optional_fields:
                    m[k] = val

        return m
