workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    Latitude.sh API:
        inputs:
            - location: https://api.latitude.sh/api-docs/v3/swagger.json
        overlays:
            - location: .speakeasy/speakeasy-modifications-overlay.yaml
        registry:
            location: registry.speakeasyapi.dev/latitude/latitude/latitude-sh-api
targets:
    latitudesh:
        target: python
        source: Latitude.sh API
        publish:
            pypi:
                token: $pypi_token
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/latitude/latitude/latitude-sh-api-python-code-samples
            labelOverride:
                fixedValue: Python (SDK)
            blocking: false
